---
- name: Make sure systemd-resolved is disabled
  ansible.builtin.systemd:
    name: systemd-resolved
    state: stopped
    enabled: false
  ignore_errors: true
  register: systemd_resolved_disabled

- name: Install required packages
  register: install_dns
  until: install_dns is succeeded
  ansible.builtin.apt:
    name:
      - openresolv
      - stubby
      - unbound
    state: present
  tags:
    - dependencies

- name: Configure stubby
  ansible.builtin.copy:
    src: stubby.yml
    dest: /etc/stubby/stubby.yml
    mode: "0444"
  notify:
    - Restart stubby

- name: Ensure stubby is enabled
  ansible.builtin.systemd:
    name: stubby
    enabled: true

- name: Configure unbound
  ansible.builtin.copy:
    src: unbound.conf
    dest: /etc/unbound/unbound.conf
    mode: "0444"
    owner: unbound
    group: unbound
  notify:
    - Reload unbound

- name: Ensures /etc/unbound/lists.d exists
  ansible.builtin.file:
    path: /etc/unbound/lists.d
    state: directory
    owner: unbound
    group: unbound
    mode: "0555"

- name: Copy dns blacklist updater script
  ansible.builtin.copy:
    src: blocklist.sh
    dest: /usr/local/bin/blocklist.sh
    mode: "0555"

- name: Add systemd timer for blocklist
  ansible.builtin.copy:
    src: systemd/blocklist.timer
    dest: /etc/systemd/system/blocklist.timer
    mode: "0640"

- name: Add systemd service for blocklist updates
  ansible.builtin.copy:
    src: systemd/blocklist.service
    dest: /etc/systemd/system/blocklist.service
    mode: "0550"

- name: Enable blocklist timer
  ansible.builtin.systemd:
    name: blocklist.timer
    enabled: true
    state: started

- name: Ensure unbound is enabled
  ansible.builtin.systemd:
    name: unbound
    enabled: true

- name: Set our local dns resolver
  ansible.builtin.lineinfile:
    path: /etc/resolvconf.conf
    regexp: ^name_servers=
    line: name_servers="::1 127.0.0.1"
    mode: "0440"
  register: resolvconfconfigure
  notify:
    - Regenerate resolvconf
