---
- ansible.builtin.include_tasks:
    file: dns.yml
    apply:
      tags:
        - dns
  tags:
    - always
- ansible.builtin.include_tasks:
    file: network-manager.yml
    apply:
      tags:
        - network-manager
  tags:
    - always
- ansible.builtin.include_tasks:
    file: wireguard.yml
    apply:
      tags:
        - wireguard
  tags:
    - always
