- hosts: all
  become: True
  gather_facts: True
  roles:
    - keyring
    - apt_transport_tor
    - debops.core
    - debops.apt_preferences
    - debops.apt
    - debops.unattanded_upgrades
    - debops-contrib.apparmor
    - debops.kmod
    - debops.grub
    - debops.sysctl
    - dev-sec.ssh-hardening
    - logind
    - debops.journald
    - debops.logrotate
    - networking
    - role: mullvad
      when: mullvad_account is defined
    - firewall
    - debops.ntp
    - display-server
    - dm
    - de
    - debops.apt_install
    - debops.python
    - packages
    - games
    - debops.docker_server
    - themes
    - fonts
    - hardware
    - bin
    - debops.locales
    - locales
    - debops.libuser
    - debops.users
    - gantsign.keyboard
    - additional_hardering
    - dev-sec.os-hardening
  vars_prompt:
    - name: local_ip
      prompt: "IP range of your home local network"
      private: no
      default: "192.168.0.0/16"
    - name: mullvad_account
      prompt: "Mullvad account number"
    - name: wireguard_server
      prompt: "Default WireGuard server"
      private: no
      default: mullvad-no1
  vars:
    # gantsign.keyboard vars
    keyboard_model: pc105
    keyboard_layout: "us,ru"
    keyboard_options: "grp:caps_toggle,compose:ralt,grp_led:scroll"
    # dev-sec vars
    sysctl_overwrite:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.ip_forward: 1
    os_desktop_enable: True
    ufw_manage_defaults: False
    ssh_server_enabled: False
    ssh_server_hardening: False
    ssh_use_dns: True
    ssh_client_hardening: True
    ssh_client_password_login: True
    os_auditd_enabled: false
    # debops vars
    ntp__daemon_enabled: True
    ntp__daemon: 'chrony'
    ntp__timezone: 'Etc/UTC'
    docker_server__upstream: True
    journald__configuration:
        - name: 'SystemMaxUse'
          value: '500M'
          state: 'present'
        - name: 'SystemKeepFree'
          value: '3G'
          state: 'present'
        - name: 'SystemMaxFiles'
          value: 10
          state: 'present'
        - name: 'MaxFileSec'
          value: '5day'
          state: 'present'
    logrotate__config:
      - state: 'present'
        options: |
          daily
          rotate 5
          create
          compress
          maxage 5
          shred
          tabooext + .dpkg-divert
          include /etc/logrotate.d
    users__accounts:
      - name: "{{ username }}"
        group: "{{ username }}"
        groups:
          - cdrom
          - floppy
          - sudo
          - audio
          - video
          - plugdev
          - netdev
          - lpadmin
          - console
          - docker
          - wireshark
          - debian-tor
          - libvirt
          - libvirt-qemu
          - kvm
        shell: '/bin/bash'
        resources:
          - 'src'
          - 'Books'
          - 'Games'
    packages:
      - haveged
      - whois
      - mlocate
      - pulseaudio
      - pulseaudio-utils
      - jq
      - pavucontrol
      - ffmpeg
      - git
      - htop
      - curl
      - wget
      - openssh-client
      - unar
      - suckless-tools
      - libavcodec-extra
      - gstreamer1.0-libav
      - gstreamer1.0-vaapi
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - ripgrep
      - maim
      - xclip
      - dnsutils
      - keepassxc
      - gimp
      - inkscape
      - audacity
      - spacefm
      - udevil
      - gvfs
      - gvfs-backends
      - sxiv
      - graphicsmagick
      - graphicsmagick-imagemagick-compat
      - pngquant
      - optipng
      - jpegoptim
      - mat2
      - nnn
      - nano
      - goldendict
      - mueller7-dict
      - dict-freedict-eng-rus
      - g++
      - gcc
      - make
      - telegram-desktop
      - needrestart
      - lm-sensors
      - playerctl
      - shellcheck
      - calcurse
      - nodejs
      - simple-scan
      - xinput
      - fuse
      - wireshark
      - devscripts
      - build-essential
      - debhelper
      - secure-delete
      - command-not-found
      - apt-file
      - direnv
      - appstream
      - libvips-tools
      - tb-starter
      - tb-updater
      - p7zip-full
      - openclipart-svg
      - beignet-opencl-icd
    apt_install__all_packages:
      - "{{ packages }}"
    apt_preferences__list:
      - packages:
          - telegram-desktop
          - nheko
          - tlp
          - tlp-rdw
          - shellcheck
          - josm
          - jmapviewer
          - wireguard
          - wireguard-dkms
          - wireguard-tools
          - unclutter-xfixes
          - unclutter-startup
          - firmware-misc-nonfree
          - firmware-realtek
          - flatpak
          - libostree-1-1
          - bubblewrap
          - xdg-desktop-portal
          - xdg-desktop-portal-gtk
          - virt-manager
          - virtinst
          - libreoffice-writer
          - libreoffice-calc
          - libreoffice-impress
          - libreoffice-draw
          - libreoffice-base-core
          - libreoffice-core
          - libreoffice-common
          - libuno-cppu3
          - libuno-cppuhelpergcc3-3
          - libuno-sal3
          - libuno-salhelpergcc3-3
          - uno-libs-private
          - ure
          - libreoffice-gtk3
          - keepassxc
          - git
          - git-man
          - git-cvs
          - git-daemon-sysvinit
          - git-daemon-run
          - git-doc
          - git-el
          - git-email
          - git-gui
          - git-mediawiki
          - git-svn
          - gitk
          - gitweb
          - golang
          - golang-doc
          - golang-go
          - golang-src
          - 'golang-1.*'
        suffix: '_backports'
        backports: [ 'buster' ]
      - '{{ apt_preferences__preset_list | list }}'
      - package: '*'
        suffix: '_tor'
        raw: |
          Explanation: Prefer official tor packages
          Package: *
          Pin: release o=TorProject,n={{ ansible_distribution_release }}
          Pin-Priority: 900
    apt_install__default_alternatives:
      - name: 'editor'
        path: '/usr/bin/nano'
    apt__install_recommends: False
    apt__install_suggests: False
    apt__repositories:
      - repo: 'deb [arch=amd64] tor+http://vwakviie2ienjx6t.onion/debian testing main'
      - repo: 'deb [arch=amd64] tor+http://vwakviie2ienjx6t.onion/debian unstable main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/repo.i2pd.xyz-keyring.gpg] tor+https://repo.i2pd.xyz/debian {{ ansible_distribution_release }} main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/deb.nodesource.com-keyring.gpg] tor+https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/vscodium-keyring.gpg] tor+https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] tor+http://sdscoq7snqtznauu.onion//torproject.org {{ ansible_distribution_release }} main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/download.docker.com-keyring.gpg] tor+https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/whonix.org-keyring.gpg] tor+http://deb.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion {{ ansible_distribution_release }} main'
      - repo: 'deb-src [signed-by=/usr/share/keyrings/uget-keyring.gpg] tor+http://ppa.launchpad.net/uget-team/ppa/ubuntu bionic main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/dl.yarnpkg.com-keyring.gpg] tor+https://dl.yarnpkg.com/debian/ stable main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/apt.qm64.tech-keyring.gpg] https://apt.qm64.tech/ apt/'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/apt.syncthing.net-keyring.gpg] tor+https://apt.syncthing.net/ syncthing stable'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/brave-keyring.gpg] tor+https://brave-browser-apt-release.s3.brave.com/ stable main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/deb.imaginary.stream-keyring.gpg] tor+https://deb.imaginary.stream {{ ansible_distribution_release }} main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/ungoogled-chromium-keyring.gpg] tor+http://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Buster/ / '
    apt__default_sources:
      - uri: 'tor+http://vwakviie2ienjx6t.onion/debian'
        comment: 'Official Debian repositories'
        distribution: 'Debian'
        state: 'present'
    apt__security_sources:
      - uri: 'tor+http://sgvtcaew4bxjd7ln.onion'
        comment: 'Debian Security repository'
        type: 'deb'
        suite: '{{ ansible_distribution_release + "/updates" }}'
        components: ['main', 'contrib', 'non-free']
        distribution: 'Debian'
        state: 'present'
    apt__nonfree: True
    apparmor__mail_to: False
    sysctl__parameters:
      - name: virtual_memory
        comment: 'https://wiki.archlinux.org/index.php/Sysctl#Virtual_memory'
        options:
          - 'vm.dirty_ratio': 3
          - 'vm.dirty_background_ratio': 2
          - 'vm.swappiness': 0
          - 'vm.vfs_cache_pressure': 50
      - name: inotify
        options:
          - 'fs.inotify.max_user_watches': 204800
    python__v3: True
    python__v2: True
    python__packages2:
      - python-dev
    python__packages3:
      - python3-dev
    locales__list:
      - 'ru_RU.UTF-8'
      - 'en_DK.UTF-8'
    locales__packages:
      - localepurge
      - mythes-en-us
      - mythes-ru
      - hunspell-en-us
      - hunspell-ru
      - hyphen-en-us
      - hyphen-ru
      - irussian
      - iamerican
      - iamerican-large
      - aspell-ru
      - enchant
    locales__system_lang: 'en_US.UTF-8'
    kmod__modules:
      - name: 'pcspkr'
        state: 'blacklist'
        comment: 'Disable PC Speaker support'
      - name: 'tcp_lp'
        state: 'present'
      - name: 'thinkpad_acpi'
        comment: 'Enable fan speed control for "thinkfan"'
        state: '{{ "present" if (thinkpad_x230|d(False) == True) else "absent" }}'
        options:
          - fan_control: 1
    grub__timeout_hardware: 1
    grub__timeout_virtual: 1
    grub__configuration:
      - name: 'cmdline_linux_default'
        value:
          # apparmor
          - 'apparmor=1'
          - 'security=apparmor'
          # disable watchdog
          - nowatchdog
          - modprobe.blacklist=iTCO_wdt
          - modprobe.blacklist=iTCO_vendor_support
          - kernel.nmi_watchdog=0
          # disable sss
          - libahci.ignore_sss=1
          # silent boot
          # https://wiki.archlinux.org/index.php/Silent_boot
          - quiet
          - 'loglevel=3'
          - 'rd.systemd.show_status=auto'
          - 'rd.udev.log_priority=3'
          - 'vt.global_cursor_default=0'
          - 'i915.fastboot=1'
