- hosts: all
  become: True
  gather_facts: True
  collections:
    - devsec.hardening
    - debops.debops
    - debops.roles01
    - debops.roles02
    - debops.roles03
    - community.general
    - ansible.posix
  roles:
    - role: remote_keyring
      tags:
        - repos
    - role: apt_transport_tor
      tags:
        - repos
    - role: apt_preferences
      tags:
        - repos
    # TODO enable and move to systemd-boot
    # - boot_manager
    - role: grub
      tags:
        - boot
    - role: swapfile
      tags:
        - swap
        - optimizations
    - role: apt
      tags:
        - repos
    - unattended_upgrades
    - kmod
    - sysctl
    - sysfs
    - role: ssh_hardening
      tags:
        - hardering
    - logind
    - role: journald
      tags:
        - logs
    - role: logrotate
      tags:
        - logs
    - role: networking
      tags:
        - networking
    - role: mullvad
      when: mullvad_account is defined
      tags:
        - mullvad
    - role: audio
      tags:
        - audio
    - role: firewall
      tags:
        - firewall
    - role: timezone
      tags:
        - time
    - role: ntp
      tags:
        - time
    - role: packages
      tags:
        - packages
    - role: dm
      tags:
        - dm
    - role: de
      tags:
        - de
    - role: apt_install
      tags:
        - packages
    - role: python
      tags:
        - python
    - role: libvirtd
      tags:
        - libvirtd
    - role: nodejs
      tags:
        - nodejs
    - role: games
      tags:
        - games
    - role: themes
      tags:
        - theme
    - role: fonts
      tags:
        - fonts
    - role: hardware
      tags:
        - hardware
    # - bin
    - role: locales
      tags:
        - locale
    - role: additional_locales
      tags:
        - locale
    - role: libuser
      tags:
        - users
    - role: users
      tags:
        - users
    - gantsign.keyboard
    - role: additional_hardering
      tags:
        - hardering
    - role: apparmor_profiles
      tags:
        - hardering
    - role: os_hardening
      tags:
        - hardering
  vars_prompt:
    - name: local_ip
      prompt: "IP range of your home local network"
      private: no
      default: "192.168.0.0/16"
    # - name: homeserver_ip
    #   prompt: "IP address of your home server"
    #   private: no
    #   default: "192.168.1.1"
    - name: mullvad_account
      prompt: "Mullvad account number"
    - name: wireguard_server
      prompt: "Default WireGuard server"
      private: no
      default: mullvad-no1
    - name: large_dirs
      prompt: "Large dirs storage prefix (e.g XDG user dirs)"
      private: no
      default: "/data"
    # - name: root_disk
    #   prompt: "Disk hosting /boot directory"
    #   private: no
    #   default: "sdb3"
  vars:
    tor_browser_user_agent: "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
    timezone: 'Etc/UTC'
    # gantsign.keyboard vars
    keyboard_model: pc105
    keyboard_layout: "us,ru"
    keyboard_options: "grp:caps_toggle,compose:ralt,grp_led:scroll"
    # dev-sec vars
    sysctl_overwrite:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.ip_forward: 1
      kernel.unprivileged_userns_clone: 1
    os_auth_retries: 10
    os_filesystem_whitelist:
      - squashfs
    os_desktop_enable: True
    ufw_manage_defaults: False
    ssh_server_enabled: False
    ssh_server_hardening: False
    ssh_use_dns: True
    ssh_client_hardening: True
    ssh_client_password_login: True
    os_auditd_enabled: false
    hidepid_option: 0
    # debops vars
    swapfile__size: 2048
    ntp__daemon_enabled: True
    ntp__daemon: 'chrony'
    ntp__timezone: "{{ timezone }}"
    journald__configuration:
        - name: 'SystemMaxUse'
          value: '500M'
          state: 'present'
        - name: 'SystemKeepFree'
          value: '3G'
          state: 'present'
        - name: 'SystemMaxFiles'
          value: 10
          state: 'present'
        - name: 'MaxFileSec'
          value: '3day'
          state: 'present'
    logrotate__config:
      - state: 'present'
        options: |
          daily
          rotate 2
          create
          compress
          maxage 3
          shred
          tabooext + .dpkg-divert
          include /etc/logrotate.d
    users__accounts:
      - name: "{{ username }}"
        group: "{{ username }}"
        groups:
          - cdrom
          - floppy
          - sudo
          - audio
          - video
          - plugdev
          - netdev
          - lpadmin
          - console
          - wireshark
          - debian-tor
          - libvirt
          - libvirt-qemu
          - kvm
          - boinc
        shell: '/bin/bash'
    nodejs__node_upstream: True
    nodejs__yarn_upstream: True
    nodejs__node_upstream_release: 'node_16.x'
    nodejs__yarn_upstream_repository: 'deb [arch=amd64 signed-by=/usr/share/keyrings/dl.yarnpkg.com-keyring.gpg] tor+https://dl.yarnpkg.com/debian/ stable main'
    nodejs__node_upstream_repository: 'deb [arch=amd64 signed-by=/usr/share/keyrings/deb.nodesource.com-keyring.gpg] tor+https://deb.nodesource.com/{{ nodejs__node_upstream_release }} {{ ansible_distribution_release }} main'
    packages:
      - haveged
      - whois
      - plocate
      - jq
      - pavucontrol
      - ffmpeg
      - git
      - htop
      - curl
      - wget
      - openssh-client
      - unar
      - suckless-tools
      - libavcodec-extra
      - gstreamer1.0-libav
      - gstreamer1.0-vaapi
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - ripgrep
      - dnsutils
      - gimp
      - inkscape
      - audacity
      - spacefm
      - udevil
      - gvfs
      - gvfs-backends
      - imv
      - pngquant
      - optipng
      - jpegoptim
      - mat2
      - nnn
      - nano
      - g++
      - gcc
      - make
      - telegram-desktop
      - needrestart
      - lm-sensors
      - shellcheck
      - fuse
      - wireshark
      - devscripts
      - build-essential
      - debhelper
      - secure-delete
      - command-not-found
      - apt-file
      - direnv
      - libvips-tools
      - p7zip-full
      - openclipart-svg
      - beignet-opencl-icd
      - v4l2loopback-dkms
      - nfs-common
      - nfs-kernel-server
      - timidity
      - fluid-soundfont-gm
    apt_install__all_packages:
      - "{{ packages }}"
    apt_preferences__list:
      - packages:
          - telegram-desktop
        suffix: '_backports'
        backports: [ 'bullseye' ]
      - '{{ apt_preferences__preset_list | list }}'
      - package: '*'
        suffix: '_tor'
        raw: |
          Explanation: Prefer official tor packages
          Package: *
          Pin: release o=TorProject,n={{ ansible_distribution_release }}
          Pin-Priority: 900
    apt_install__default_alternatives:
      - name: 'editor'
        path: '/usr/bin/micro'
    apt__install_recommends: False
    apt__install_suggests: False
    apt__repositories:
      - repo: 'deb [arch=amd64] tor+http://2s4yqjx5ul6okpp3f2gaunr2syex5jgbfpfvhxxbbjwnrsvbk5v3qbid.onion/debian testing main'
      - repo: 'deb [arch=amd64] tor+http://2s4yqjx5ul6okpp3f2gaunr2syex5jgbfpfvhxxbbjwnrsvbk5v3qbid.onion/debian unstable main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/repo.i2pd.xyz-keyring.gpg] tor+https://repo.i2pd.xyz/debian {{ ansible_distribution_release }} main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/vscodium-keyring.gpg] tor+https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/debs vscodium main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] tor+http://apow7mjfryruh65chtdydfmqfpj5btws7nbocgtaovhvezgccyjazpqd.onion/torproject.org {{ ansible_distribution_release }} main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/whonix.org-keyring.gpg] tor+http://deb.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion {{ ansible_distribution_release }} main'
      - repo: 'deb-src [signed-by=/usr/share/keyrings/uget-keyring.gpg] tor+http://ppa.launchpad.net/uget-team/ppa/ubuntu bionic main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/apt.syncthing.net-keyring.gpg] tor+https://apt.syncthing.net/ syncthing stable'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/deb.imaginary.stream-keyring.gpg] tor+https://deb.imaginary.stream {{ ansible_distribution_release }} main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/jami-archive-keyring.gpg] tor+https://dl.jami.net/nightly/debian_11/ ring main'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/ungoogled-chromium-keyring.gpg] tor+https://download.opensuse.org/repositories/home:/ungoogled_chromium/Debian_Bullseye/ /'
      - repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/gvisor.gpg] tor+https://storage.googleapis.com/gvisor/releases release main'
    apt__default_sources:
      - uri: 'tor+http://2s4yqjx5ul6okpp3f2gaunr2syex5jgbfpfvhxxbbjwnrsvbk5v3qbid.onion/debian'
        comment: 'Official Debian repositories'
        distribution: 'Debian'
        state: 'present'
    apt__security_sources:
      - uri: 'tor+http://5ajw6aqf3ep7sijnscdzw77t7xq4xjpsy335yb2wiwgouo7yfxtjlmid.onion/debian-security'
        comment: 'Debian Security repository'
        type: 'deb'
        suite: '{{ ansible_distribution_release + "-security" }}'
        components: ['main', 'contrib', 'non-free']
        distribution: 'Debian'
        state: 'present'
    apt__nonfree: True
    apparmor__mail_to: False
    sysctl__parameters:
      - name: virtual_memory
        comment: 'https://wiki.archlinux.org/index.php/Sysctl#Virtual_memory'
        options:
          - 'vm.dirty_ratio': 3
          - 'vm.dirty_background_ratio': 2
          - 'vm.swappiness': 5
          - 'vm.vfs_cache_pressure': 50
      - name: inotify
        options:
          - 'fs.inotify.max_user_watches': 4194304
          - 'fs.inotify.max_user_instances': 8192
      - name: net
        options:
          - 'net.core.netdev_max_backlog': 16384
          - 'net.core.somaxconn': 8192
          - 'net.ipv4.tcp_fastopen': 3
    sysfs__attributes:
      - name: 'governor'
        state: 'defined'
        options:
          - name: 'devices/system/cpu/cpu0/cpufreq/scaling_governor'
            value: 'performance'
    python__v3: True
    python__v2: False
    python__packages3:
      - python3-dev
      - python-is-python3
    locales__list:
      - 'ru_RU.UTF-8'
      - 'en_DK.UTF-8'
    locales__packages:
      - localepurge
      - mythes-en-us
      - mythes-ru
      - hunspell-en-us
      - hunspell-ru
      - myspell-ru
      - hyphen-en-us
      - hyphen-ru
      - irussian
      - iamerican
      - iamerican-large
      - aspell-ru
      - enchant
    locales__system_lang: 'en_US.UTF-8'
    kmod__load:
      - name: 'tun'
      - name: 'v4l2loopback'
    kmod__modules:
      - name: 'pcspkr'
        state: 'blacklist'
        comment: 'Disable PC Speaker support'
      - name: 'p_lkrg'
        state: 'present'
      - name: 'v4l2loopback'
        state: 'present'
        options:
          - name: devices
            value: "1"
          - name: card_label
            value: "Webcam"
          - name: exclusive_caps
            value: "1"
      - name: 'thinkpad_acpi'
        comment: 'Enable fan speed control for "thinkfan"'
        state: '{{ "present" if (thinkpad_x230|d(False) == True) else "absent" }}'
        options:
          - fan_control: 1
    grub__timeout_hardware: 1
    grub__timeout_virtual: 1
    grub__configuration:
      - name: 'cmdline_linux_default'
        value:
          # zswap
          - 'zswap.enabled=1'
          - 'zswap.compressor=zstd'
          - 'zswap.max_pool_percent=15'
          # apparmor
          - 'apparmor=1'
          - 'security=apparmor'
          # disable watchdog
          - nowatchdog
          - modprobe.blacklist=iTCO_wdt
          - modprobe.blacklist=iTCO_vendor_support
          - nmi_watchdog=0
          # disable sss
          - libahci.ignore_sss=1
          # silent boot
          # https://wiki.archlinux.org/index.php/Silent_boot
          - quiet
          - 'loglevel=3'
          - 'rd.systemd.show_status=auto'
          - 'rd.udev.log_level=3'
          - 'vt.global_cursor_default=0'
          # required by oomd
          - 'swapaccount=1'
          - 'systemd.unified_cgroup_hierarchy=1'
