- hosts: all
  become: True
  gather_facts: True
  roles:
    - apt_transport_tor
    - debops.core
    - debops.apt_preferences
    - debops.apt
    - debops.unattanded_upgrades
    - debops-contrib.apparmor
    - debops.kmod
    - debops.grub
    - debops.sysctl
    - dev-sec.ssh-hardening
    - logind
    - networking
    - role: mullvad
      when: mullvad_account is defined
    - firewall
    - debops.ntp
    - display-server
    - dm
    - de
    - debops.apt_install
    - debops.python
    - packages
    - debops.docker_server   
    - themes
    - fonts
    - hardware
    - bin
    - debops.locales
    - locales
    - debops.libuser
    - debops.users
    - gantsign.keyboard
    - additional_hardering
    - dev-sec.os-hardening
  vars_prompt:
    - name: local_ip
      prompt: "IP range of your home local network"
      private: no
      default: "192.168.0.0/16"
    - name: mullvad_account
      prompt: "Mullvad account number"
    - name: wireguard_server
      prompt: "Default WireGuard server"
      private: no
      default: mullvad-no1
  vars:
    # gantsign.keyboard vars
    keyboard_model: pc105
    keyboard_layout: "us,ru"
    keyboard_options: "grp:caps_toggle,compose:ralt,grp_led:scroll"
    # dev-sec vars
    sysctl_overwrite:
      net.ipv6.conf.all.disable_ipv6: 0
      net.ipv4.ip_forward: 1
    os_desktop_enable: True
    ufw_manage_defaults: False
    ssh_server_enabled: False
    ssh_server_hardening: False
    ssh_use_dns: True
    ssh_client_hardening: True
    ssh_client_password_login: True
    # debops vars
    ntp__daemon_enabled: True
    ntp__daemon: 'chrony'
    ntp__timezone: 'Etc/UTC'
    docker_server__upstream: True
    users__accounts:
      - name: "{{ username }}"
        group: "{{ username }}"
        groups:
          - cdrom
          - floppy
          - sudo
          - audio
          - video
          - plugdev
          - netdev
          - lpadmin
          - console
          - docker
          - wireshark
          - debian-tor
        shell: '/bin/bash'
        resources:
          - 'src'
          - 'Books'
          - 'Games'
    packages:
      - haveged
      - whois
      - mlocate
      - pulseaudio
      - pulseaudio-utils
      - jq
      - pavucontrol
      - ffmpeg
      - git
      - htop
      - curl
      - wget
      - openssh-client
      - unar
      - suckless-tools
      - libavcodec-extra
      - gstreamer1.0-libav
      - gstreamer1.0-vaapi
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - ripgrep
      - maim
      - xclip
      - dnsutils
      - keepassxc
      - gimp
      - inkscape      
      - chromium
      - chromium-sandbox
      - audacity
      - spacefm
      - udevil
      - gvfs
      - gvfs-backends
      - sxiv
      - graphicsmagick
      - graphicsmagick-imagemagick-compat
      - pngquant
      - optipng
      - jpegoptim
      - mat2
      - nnn
      - nano
      - goldendict
      - mueller7-dict
      - dict-freedict-eng-rus
      - vagrant
      - vagrant-cachier
      - g++
      - gcc
      - make
      - telegram-desktop
      - needrestart
      - lm-sensors
      - playerctl
      - shellcheck
      - calcurse
      - nodejs
      - simple-scan
      - xinput
      - fuse
      - wireshark
      - devscripts
      - build-essential
      - debhelper
      - secure-delete
      - command-not-found
      - apt-file
      - direnv
      - appstream
      - libvips-tools
      - tb-starter
      - tb-updater
    apt_install__all_packages:
      - "{{ packages }}"
    apt_preferences__list:
      - packages:
          - telegram-desktop
          - nheko
          - tlp
          - tlp-rdw
          - shellcheck
          - josm
          - jmapviewer
          - wireguard
          - wireguard-dkms
          - wireguard-tools
          - unclutter-xfixes
          - unclutter-startup
          - firmware-misc-nonfree
          - firmware-realtek
          - flatpak
          - libostree-1-1
          - bubblewrap
          - xdg-desktop-portal
          - xdg-desktop-portal-gtk
        suffix: '_backports'
        backports: [ 'buster' ]
      - '{{ apt_preferences__preset_list | list }}'
      - package: '*'
        suffix: '_tor'
        raw: |
          Explanation: Prefer official tor packages
          Package: *
          Pin: release o=TorProject,n={{ ansible_distribution_release }}
          Pin-Priority: 900
    apt_install__default_alternatives:
      - name: 'editor'
        path: '/usr/bin/nano'
    apt__install_recommends: False
    apt__install_suggests: False
    apt__repositories:
      - repo: 'deb [arch=amd64] tor+http://vwakviie2ienjx6t.onion/debian testing main'
      - repo: 'deb [arch=amd64] tor+http://vwakviie2ienjx6t.onion/debian unstable main'
      - repo: 'deb [arch=amd64 signed-by=951928BB317024EFD053D73C66F6C87B98EBCFE2] tor+https://repo.i2pd.xyz/debian {{ ansible_distribution_release }} main'
      - repo: 'deb [arch=amd64 signed-by=9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280] tor+https://deb.nodesource.com/node_12.x {{ ansible_distribution_release }} main'
      - repo: 'deb [arch=amd64 signed-by=1302DE60231889FE1EBACADC54678CF75A278D9C] https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/repos/debs/ vscodium main'
      - repo: 'deb [arch=amd64 signed-by=A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89] tor+http://sdscoq7snqtznauu.onion//torproject.org {{ ansible_distribution_release }} main'
      - repo: 'deb [arch=amd64 signed-by=9DC858229FC7DD38854AE2D88D81803C0EBFCD88] tor+https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
      - repo: 'deb [arch=amd64 signed-by=916B8D99C38EAF5E8ADC7A2A8D66066A2EEACCDA] tor+http://deb.dds6qkxpwdeubwucdiaord2xgbbeyds25rbsgr73tbfpqpt4a6vjwsyd.onion {{ ansible_distribution_release }} main'
      - repo: 'deb-src [signed-by=0EA6702BA573945278AD7EF0658BF4D7EE19FA85] tor+http://ppa.launchpad.net/uget-team/ppa/ubuntu bionic main'
      - repo: 'deb [arch=amd64 signed-by=72ECF46A56B4AD39C907BBB71646B01B86E50310] tor+https://dl.yarnpkg.com/debian/ stable main'
      - repo: 'deb [arch=amd64 signed-by=7BD7D7DD3E220E0EB7389AF39731AA2171096268] https://apt.qm64.tech/ apt/'
      - repo: 'deb [arch=amd64 signed-by=37C84554E7E0A261E4F76E1ED26E6ED000654A3E] tor+https://apt.syncthing.net/ syncthing stable'
      - repo: 'deb [arch=amd64 signed-by=A338F71A89CD06FD5F9718582F7F0DA5FD5B64B9] tor+http://download.opensuse.org/repositories/home:/strycore/Debian_10/ ./'
    apt__default_sources:
      - uri: 'tor+http://vwakviie2ienjx6t.onion/debian'
        comment: 'Official Debian repositories'
        distribution: 'Debian'
        state: 'present'
    apt__security_sources:
      - uri: 'tor+http://sgvtcaew4bxjd7ln.onion'
        comment: 'Debian Security repository'
        type: 'deb'
        suite: '{{ ansible_distribution_release + "/updates" }}'
        components: ['main', 'contrib', 'non-free']
        distribution: 'Debian'
        state: 'present'
    apt__keys:
      - id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
        url: 'https://download.docker.com/linux/debian/gpg'
      - id: '951928BB317024EFD053D73C66F6C87B98EBCFE2'
        url: 'https://repo.i2pd.xyz/r4sas.gpg'
      - id: '9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280'
        url: 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
      #- id: 'D43F640145369C51D786DDEA76F1A20FF987672F'
      #  url: 'https://dl.winehq.org/wine-builds/winehq.key'
      - id: '37C84554E7E0A261E4F76E1ED26E6ED000654A3E'
        url: 'https://syncthing.net/release-key.txt'
      - id: '1302DE60231889FE1EBACADC54678CF75A278D9C'
        url: 'https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg'
      - id: 'A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89'
        url: 'https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc'
      - id: '0EA6702BA573945278AD7EF0658BF4D7EE19FA85'
        keyserver: 'keyserver.ubuntu.com'
      - id: 'E4BD026BDFED8174F99510D94805D371C605B120'
        url: 'https://www.whonix.org/patrick.asc'
      - id: '72ECF46A56B4AD39C907BBB71646B01B86E50310'
        url: https://dl.yarnpkg.com/debian/pubkey.gpg
      - id: '7BD7D7DD3E220E0EB7389AF39731AA2171096268'
        url: https://apt.qm64.tech/key.public.asc
      - id: 'A338F71A89CD06FD5F9718582F7F0DA5FD5B64B9'
        url: https://download.opensuse.org/repositories/home:/strycore/Debian_10/Release.key
    apt__nonfree: True
    apparmor__mail_to: False
    sysctl__parameters:
      - name: virtual_memory
        comment: 'https://wiki.archlinux.org/index.php/Sysctl#Virtual_memory'
        options:
          - 'vm.dirty_ratio': 3
          - 'vm.dirty_background_ratio': 2
          - 'vm.swappiness': 0
          - 'vm.vfs_cache_pressure': 50
      - name: inotify
        options:
          - 'fs.inotify.max_user_watches': 204800
    python__v3: True
    python__v2: True
    python__packages2:
      - python-dev
    python__packages3:
      - python3-dev
    locales__list:
      - 'ru_RU.UTF-8'
      - 'en_DK.UTF-8'
    locales__packages:
      - mythes-en-us
      - mythes-ru
      - hunspell-en-us
      - hunspell-ru
      - hyphen-en-us
      - hyphen-ru
      - irussian
      - iamerican
      - iamerican-large
      - aspell-ru
      - enchant
    locales__system_lang: 'en_US.UTF-8'
    kmod__modules:
      - name: 'pcspkr'
        state: 'blacklist'
        comment: 'Disable PC Speaker support'
      - name: 'tcp_lp'
        state: 'present'
      - name: 'thinkpad_acpi'
        comment: 'Enable fan speed control for "thinkfan"'
        state: '{{ "present" if (thinkpad_x230|d(False) == True) else "absent" }}'
        options:
          - fan_control: 1
    grub__timeout_hardware: 1
    grub__timeout_virtual: 1
    grub__configuration:
      - name: 'cmdline_linux_default'
        value:
          # apparmor
          - 'apparmor=1'
          - 'security=apparmor'
          # disable watchdog
          - nowatchdog
          - modprobe.blacklist=iTCO_wdt
          - modprobe.blacklist=iTCO_vendor_support
          - kernel.nmi_watchdog=0
          # disable sss
          - libahci.ignore_sss=1
          # silent boot
          # https://wiki.archlinux.org/index.php/Silent_boot
          - quiet
          - 'loglevel=3'
          - 'rd.systemd.show_status=auto'
          - 'rd.udev.log_priority=3'
          - 'vt.global_cursor_default=0'
          - 'i915.fastboot=1'