collections:
  - name: debops.debops
    source: https://galaxy.ansible.com
    version: "3.2.2"
  - name: devsec.hardening
    source: https://galaxy.ansible.com
    version: "10.0.0"
  - name: community.general
    source: https://galaxy.ansible.com
  - name: ansible.posix
    source: https://galaxy.ansible.com
roles:
  - name: gantsign.keyboard
    src: git+https://github.com/gantsign/ansible-role-keyboard.git
    version: 372f2973fdec81ee503324c787e15842c2bc0f44
