---
- name: Change behaviour of power button and lid switch
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    insertafter: ^\[Login\]
    line: "{{ item }}"
  loop:
    - HandlePowerKey=ignore
    - HandleLidSwitch=suspend
    - HandleLidSwitchExternalPower=lock
    - HandleLidSwitchDocked=lock
    - IdleAction=lock
    - IdleActionSec=300
