---
- name: Install Bisq from flatpak
  become: true
  become_user: "{{ username }}"
  flatpak:
    name: network.bisq.Bisq
    state: present

# - name: Ensures ~/.local/share/Bisq exists
#   file:
#     path: /home/{{ username }}/.local/share/Bisq
#     mode: 0750
#     state: directory
#     owner: "{{ username }}"
#     group: "{{ username }}"

# - name: Configure bisq
#   lineinfile:
#     path: /home/{{ username }}/.local/share/Bisq/bisq.properties
#     regexp: ^{{ item.name }}
#     line: "{{ item.name }}={{ item.value }}"
#     create: true
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: 0440
#   loop:
#     - name: torControlCookieFile
#       value: /run/tor/control.authcookie
#     - name: torControlUseSafeCookieAuth
#       value: "true"
#     - name: torControlPort
#       value: "9051"
    #- name: 'rpcUser'
    #  value: "{{ bitcoinrpc_user }}"
    #- name: 'rpcPassword'
    #  value: "{{ lookup('password', 'credentials/bitcoind/rpcpass length=20') }}"
    #- name: 'rpcBlockNotificationPort'
    #  value: '5120'
    #- name: 'fullDaoNode'
    #  value: 'true'
    #- name: 'rpcHost'
    #  value: '127.0.0.1'
    #- name: 'rpcBlockNotificationHost'
    #  value: '127.0.0.1'
    #- name: 'rpcPort'
    #  value: '8333'
