---
- name: Install electrum
  ansible.builtin.apt:
    name:
      - electrum
      - python3-qdarkstyle
      - python3-btchip
      - python3-trezor
      - python3-zbar
    state: present

- name: Ensures ~/.electrum exists
  ansible.builtin.file:
    path: /home/{{ username }}/.electrum
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Configure electrum
  ansible.builtin.copy:
    src: electrum/config
    dest: /home/{{ username }}/.electrum/config
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install wasabiwallet from flatpak
  become: true
  become_user: "{{ username }}"
  community.general.flatpak:
    name: io.wasabiwallet.WasabiWallet
    state: present

- name: Ensures ~/.var/io.wasabiwallet.WasabiWallet/.walletwasabi/client exists
  ansible.builtin.file:
    path: /home/{{ username }}/.var/app/io.wasabiwallet.WasabiWallet/.walletwasabi/client
    mode: "0750"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure wasabi wallet ui
  ansible.builtin.copy:
    src: walletwasabi/UiConfig.json
    dest: /home/{{ username }}/.var/app/io.wasabiwallet.WasabiWallet/.walletwasabi/client/UiConfig.json
    mode: "0440"
    owner: "{{ username }}"
    group: "{{ username }}"
