---
- name: Install electrum
  apt:
    name:
      - electrum
      - python3-btchip
      - python3-trezor
      - python3-zbar
    state: present

- name: Ensures ~/.electrum exists
  file:
    path: /home/{{ username }}/.electrum
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0750

- name: Configure electrum
  copy:
    src: electrum/config
    dest: /home/{{ username }}/.electrum/config
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install wasabiwallet from flatpak
  become: true
  become_user: "{{ username }}"
  flatpak:
    name: io.wasabiwallet.WasabiWallet
    state: present

- name: Ensures ~/.var/io.wasabiwallet.WasabiWallet/.walletwasabi/client exists
  file:
    path: /home/{{ username }}/.var/io.wasabiwallet.WasabiWallet/.walletwasabi/client
    mode: 0750
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure wasabi wallet ui
  copy:
    src: walletwasabi/UiConfig.json
    dest: "/home/{{ username }}/.var/io.wasabiwallet.WasabiWallet/.walletwasabi/client/UiConfig.json"
    mode: 0440
    owner: "{{ username }}"
    group: "{{ username }}"
