- name: Make sure chromium is not installed
  apt:
    name:
      - chromium
      - chromium-sandbox
    state: absent

- name: Install Ungoogled-Chromium
  apt:
    name: ungoogled-chromium
    state: present

- name: Configure chromium
  copy:
    src: 'chromium/additional-flags'
    dest: "/etc/chromium.d/additional-flags"