- name: Make sure chromium is not installed
  apt:
    name:
      - chromium
      - chromium-sandbox
    state: absent

- name: Install Ungoogled-Chromium
  apt:
    name: ungoogled-chromium
    state: present

- name: Configure chromium
  copy:
    src: 'chromium/chromium-flags.conf'
    dest: "/home/{{ username }}/.config/chromium-flags.conf"
    mode: '0640'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy desktop files for web apps
  copy:
    src: "applications/{{ item }}.desktop"
    dest: "/home/{{ username }}/.local/share/applications/{{ item }}.desktop"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - github
    - clickup
    - slack
    - figma
    - firebase
    - gcloud
    - gitlab