
- name: Make sure chromium is not installed
  apt:
    name:
      - chromium
      - chromium-sandbox
    state: absent

- name: Install ungoogled-chromium
  apt:
    name:
      - ungoogled-chromium
      - ungoogled-chromium-sandbox
    state: present

- name: Configure chromium
  template:
    src: 'chromium/chromium-flags.conf.j2'
    dest: "/home/{{ username }}/.config/chromium-flags.conf"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"