---
- name: Make sure ungoogled-chromium is not installed
  ansible.builtin.apt:
    name:
      - ungoogled-chromium
      - ungoogled-chromium-dbgsym
    state: absent

- name: Install chromium
  register: install_chromium
  until: install_chromium is succeeded
  ansible.builtin.apt:
    name:
      - chromium
      - webext-ublock-origin-chromium
    state: present

- name: Add script to source chromium-flags.conf
  ansible.builtin.copy:
    src: chromium/chromium-flags.sh
    dest: /etc/chromium.d/chromium-flags
    mode: +x

- name: Configure chromium
  ansible.builtin.copy:
    src: chromium/chromium-flags.conf
    dest: /home/{{ username }}/.config/chromium-flags.conf
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Ensure extensions directory exists
  ansible.builtin.file:
    dest: /usr/share/chromium/extensions
    state: directory
    mode: "0755"

- name: Copy desktop files for web apps
  ansible.builtin.template:
    src: applications/chromium-web-app.desktop.j2
    dest: /home/{{ username }}/.local/share/applications/{{ item.name }}.desktop
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ webapps }}"
