
- name: Make sure chromium is not installed with apt
  apt:
    name:
      - chromium
      - chromium-sandbox
      - ungoogled-chromium
      - ungoogled-chromium-sandbox
    state: absent

- name: Install Ungoogled Chromium from flatpak
  flatpak:
    name: com.github.Eloston.UngoogledChromium
    state: present

- name: Ensures ~/.var/app/com.github.Eloston.UngoogledChromium/config exists
  file:
    path: "/home/{{ username }}/.var/app/com.github.Eloston.UngoogledChromium/config"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure chromium
  copy:
    src: 'chromium/chromium-flags.conf'
    dest: "/home/{{ username }}/.var/app/com.github.Eloston.UngoogledChromium/config/chromium-flags.conf"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"