- name: Install dcnnt
  become: yes
  become_user: "{{ username }}"
  shell: "pipx install dcnnt"

- name: Ensures ~/.config/dcnnt/plugins exists
  file:
    path: "/home/{{ username }}/.config/dcnnt/plugins"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure dcnnt
  template:
    src: 'dcnnt/conf.json.j2'
    dest: "/home/{{ username }}/.config/dcnnt/conf.json"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure dcnnt plugins
  copy:
    src: 'dcnnt/{{ item }}'
    dest: "/home/{{ username }}/.config/dcnnt/plugins/{{ item }}"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - 'file.conf.json'
    - 'rcmd.conf.json'

- name: Configure dcnnt device
  template:
    src: 'dcnnt/65544.device.json.j2'
    dest: "/home/{{ username }}/.config/dcnnt/devices/65544.device.json"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"