---
- name: Install dictd, goldendict and some dictionaries
  register: install_dicts
  until: install_dicts is succeeded
  ansible.builtin.apt:
    name:
      - dictd
      - goldendict
      - mueller7-dict
      - dict-freedict-eng-rus
      - dict-foldoc
      - dict-gcide
      - dict-elements
    state: present

- name: Ensures ~/.goldendict exists
  ansible.builtin.file:
    path: /home/{{ username }}/.goldendict
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Configure goldendict
  ansible.builtin.copy:
    src: goldendict/config
    dest: /home/{{ username }}/.goldendict/config
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
