- name: Install uGet and aria2
  apt:
    name:
      - uget
      - aria2
    state: present

- name: Ensures ~/.config/uGet/category exists
  file:
    path: "/home/{{ username }}/.config/uGet/category"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Create uGet categories
  template:
    src: "uGet/category/{{ item }}.json.j2"
    dest: "/home/{{ username }}/.config/uGet/category/000{{ uget_category_index }}.json"
  loop:
    - 'Downloads'
    - 'Videos'
    - 'Music'
    - 'Books'
    - 'Games'
    - 'Pictures'
  loop_control:
    index_var: uget_category_index

- name: Copy uGet config
  template:
    src: uGet/Setting.json.j2
    dest: "/home/{{ username }}/.config/uGet/Setting.json"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Ensures ~/.config/aria2 exists
  file:
    path: "/home/{{ username }}/.config/aria2"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy aria2 config
  template:
    src: aria2/aria2.conf.j2
    dest: "/home/{{ username }}/.config/aria2/aria2.conf"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Add systemd service
  copy:
    src: 'systemd/aria2cd.service'
    dest: "/home/{{username}}/.config/systemd/user/aria2cd.service"
    mode: '0640'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Enable aria2cd service
  become: yes
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: aria2cd
    enabled: yes

- name: Collect package facts
  package_facts:
    manager: auto

- name: Install uget-integrator build deps
  apt:
    name: 'uget-integrator=1.0.0-1'
    state: build-dep
  when: "'uget-integrator' not in ansible_facts.packages"

- name: Build uget-integrator
  shell:
    chdir: /tmp
    cmd: 'apt source --build uget-integrator=1.0.0-1'
  when: "'uget-integrator' not in ansible_facts.packages"

- name: Install uget-integrator
  apt:
    deb: '/tmp/uget-integrator_1.0.0-1_amd64.deb'
  when: "'uget-integrator' not in ansible_facts.packages"