- name: Install aria2
  apt:
    name: aria2
    state: present

- name: Ensures ~/.config/aria2 exists
  file:
    path: "/home/{{ username }}/.config/aria2"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy aria2 config
  template:
    src: aria2/aria2.conf.j2
    dest: "/home/{{ username }}/.config/aria2/aria2.conf"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Add systemd service
  copy:
    src: 'systemd/aria2cd.service'
    dest: "/home/{{username}}/.config/systemd/user/aria2cd.service"
    mode: '0640'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Enable aria2cd service
  become: yes
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: aria2cd
    enabled: yes

- name: Install aria2p
  become: yes
  become_user: "{{ username }}"
  shell: "pipx install --force aria2p[tui]"