---
- name: Install aria2 and persepolis
  register: install_aria2
  until: install_aria2 is succeeded
  ansible.builtin.apt:
    name:
      - aria2
      - persepolis
    state: present

- name: Ensures ~/.config/aria2 exists
  ansible.builtin.file:
    path: /home/{{ username }}/.config/aria2
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Copy aria2 config
  ansible.builtin.template:
    src: aria2/aria2.conf.j2
    dest: /home/{{ username }}/.config/aria2/aria2.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0440"

- name: Add systemd service
  ansible.builtin.copy:
    src: systemd/aria2cd.service
    dest: /home/{{ username }}/.config/systemd/user/aria2cd.service
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
