- name: Download electron cash
  get_url:
    url: "https://github.com/Electron-Cash/Electron-Cash/releases/download/{{ electroncash_version }}/Electron-Cash-{{ electroncash_version }}-x86_64.AppImage"
    dest: "/usr/local/bin/electroncash"
    checksum: "{{ electroncash_checksum }}"

- name: Add executable permission
  file:
    dest: /usr/local/bin/electroncash
    mode: 'a+x'

- name: Ensures ~/.electron-cash exists
  file:
    path: "/home/{{ username }}/.electron-cash"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure electron cash
  copy:
    src: 'electron-cash/config'
    dest: "/home/{{ username }}/.electron-cash/config"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"