---
- name: Download MyCrypto
  register: get_mycrypto
  until: get_mycrypto is succeeded
  ansible.builtin.get_url:
    url: https://github.com/MyCryptoHQ/MyCrypto/releases/download/{{ mycrypto_version }}/linux-x86-64_{{ mycrypto_version }}_MyCrypto.AppImage
    dest: /usr/local/bin/mycrypto
    checksum: "{{ mycrypto_checksum }}"
    mode: "0744"

- name: Add executable permission to mycrypto
  ansible.builtin.file:
    dest: /usr/local/bin/mycrypto
    mode: "0755"

- name: Ensures ~/.local/share/applications exists
  ansible.builtin.file:
    path: /home/{{ username }}/.local/share/applications
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Copy desktop file
  ansible.builtin.copy:
    src: applications/mycrypto.desktop
    dest: /home/{{ username }}/.local/share/applications/mycrypto.desktop
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
