- name: Download MyCrypto
  get_url:
    url: "https://github.com/MyCryptoHQ/MyCrypto/releases/download/{{ mycrypto_version }}/linux-x86-64_{{ mycrypto_version }}_MyCrypto.AppImage"
    dest: "/usr/local/bin/mycrypto"
    checksum: "{{ mycrypto_checksum }}"

- name: Add executable permission to mycrypto
  file:
    dest: /usr/local/bin/mycrypto
    mode: 'a+x'

- name: Ensures ~/.local/share/applications exists
  file:
    path: "/home/{{ username }}/.local/share/applications"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy desktop file
  copy:
    src: "applications/mycrypto.desktop"
    dest: "/home/{{ username }}/.local/share/applications/mycrypto.desktop"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"