- name: Create openethereum user
  user:
    name: openethereum
    shell: /bin/false
    create_home: yes
    home: "/home/openethereum"
    system: yes

- name: Check is openethereum is installed
  stat: 
    path: "/usr/local/bin/openethereum"
  register: openethereum_exists

- name: Create temp dir for openethereum
  tempfile:
    state: directory
  register: openethereum_download_tempdir
  when: not openethereum_exists.stat.exists

- name: Get openethereum
  get_url:
    url: "https://github.com/openethereum/openethereum/releases/download/v{{ openethereum_version }}/openethereum-linux-v{{ openethereum_version }}.zip"
    dest: "{{ openethereum_download_tempdir.path }}/openethereum.zip"
    checksum: "{{ openethereum_checksum }}"
  when: not openethereum_exists.stat.exists 

- name: Unpack openethereum
  unarchive:
    src: "{{ openethereum_download_tempdir.path }}/openethereum.zip"
    dest: "/usr/local/bin"
    remote_src: True
  when: not openethereum_exists.stat.exists

- name: Add executable permission to openethereum binaries
  file:
    dest: "/usr/local/bin/{{ item }}"
    mode: 'a+x'
  loop:
    - ethkey
    - ethstore
    - openethereum-evm
    - openethereum

- name: Ensures /etc/openethereum exists
  file:
    path: "/etc/openethereum"
    state: directory

- name: Copy openethereum config
  copy:
    src: 'openethereum/config.toml'
    dest: "/etc/openethereum/config.toml"

- name: Add systemd service
  copy:
    src: 'systemd/openethereum.service'
    dest: "/etc/systemd/system/openethereum.service"
    mode: '0640'

- name: Disable openethereum service
  systemd:
    name: openethereum
    enabled: no
    state: stopped

- name: Download MyCrypto
  get_url:
    url: "https://github.com/MyCryptoHQ/MyCrypto/releases/download/{{ mycrypto_version }}/linux-x86-64_{{ mycrypto_version }}_MyCrypto.AppImage"
    dest: "/usr/local/bin/mycrypto"
    checksum: "{{ mycrypto_checksum }}"

- name: Add executable permission to mycrypto
  file:
    dest: /usr/local/bin/mycrypto
    mode: 'a+x'
