- name: Download MyCrypto
  get_url:
    url: "https://github.com/MyCryptoHQ/MyCrypto/releases/download/{{ mycrypto_version }}/linux-x86-64_{{ mycrypto_version }}_MyCrypto.AppImage"
    dest: "/usr/local/bin/mycrypto"
    checksum: "{{ mycrypto_checksum }}"

- name: Add executable permission to mycrypto
  file:
    dest: /usr/local/bin/mycrypto
    mode: 'a+x'
