---
- name: Install nnn
  register: install_nnn
  until: install_nnn is succeeded
  ansible.builtin.apt:
    name: nnn
    state: present

- name: Ensures ~/.local/share/applications exists
  ansible.builtin.file:
    path: /home/{{ username }}/.local/share/applications
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Copy desktop file
  ansible.builtin.copy:
    src: applications/nnn.desktop
    dest: /home/{{ username }}/.local/share/applications/nnn.desktop
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
