- name: Install nnn
  apt:
    name: nnn
    state: present

- name: Ensures ~/.local/share/applications exists
  file:
    path: "/home/{{ username }}/.local/share/applications"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy desktop file
  copy:
    src: "applications/nnn.desktop"
    dest: "/home/{{ username }}/.local/share/applications/nnn.desktop"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"