---
- name: Install Firefox
  register: install_firefox
  until: install_firefox is succeeded
  ansible.builtin.apt:
    name: firefox-esr
    state: present

- name: Set Firefox as default browser
  community.general.alternatives:
    link: /usr/local/bin/{{ item }}
    name: "{{ item }}"
    path: /usr/bin/firefox-esr
  loop:
    - x-www-browser
    - gnome-www-browser

- name: Ensures every profile dir exists
  ansible.builtin.file:
    path: /home/{{ username }}/.mozilla/firefox/{{ item.name }}/extensions
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"
  loop: "{{ firefox_profiles }}"

- name: Ensures ~/.mozilla/extensions exists
  ansible.builtin.file:
    path: /home/{{ username }}/.mozilla/extensions
    mode: "0750"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Ensures ~/.mozilla/managed-storage exists
  ansible.builtin.file:
    path: /home/{{ username }}/.mozilla/managed-storage
    mode: "0750"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure profiles.ini
  ansible.builtin.template:
    src: firefox/profiles.ini.j2
    dest: /home/{{ username }}/.mozilla/firefox/profiles.ini
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0440"

- name: Install ghacks-user.js for every profile
  ansible.builtin.get_url:
    url: "{{ ghacks_url }}"
    checksum: "{{ ghacks_checksum }}"
    dest: /home/{{ username }}/.mozilla/firefox/{{ item.name }}/user.js
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0440"
  loop: "{{ firefox_profiles }}"

# - name: Install firefox extensions for profiles
#   ansible.builtin.get_url:
#     url: "{{ item[1].url }}"
#     checksum: "{{ item[1].checksum }}"
#     dest: /home/{{ username }}/.mozilla/firefox/{{ item[0].name }}/extensions/{{ item[1].id }}.xpi
#     owner: "{{ username }}"
#     group: "{{ username }}"
#     mode: "0440"
#   loop: "{{ firefox_profiles | subelements('extensions', skip_missing=True) }}"

- name: Configure firefox profiles
  ansible.builtin.lineinfile:
    dest: /home/{{ username }}/.mozilla/firefox/{{ item[0].name }}/user.js
    regexp: ^user_pref\("{{ item[1].pref | regex_escape() }}",.*\)\;.*$
    line: user_pref("{{ item[1].pref }}", {{ item[1].value }});
  with_nested:
    - "{{ firefox_profiles }}"
    - "{{ firefox_default_prefs }}"

- name: Configure firefox profiles specific settings
  ansible.builtin.lineinfile:
    dest: /home/{{ username }}/.mozilla/firefox/{{ item[0].name }}/user.js
    regexp: ^user_pref\("{{ item[1].pref | regex_escape() }}",.*\)\;.*$
    line: user_pref("{{ item[1].pref }}", {{ item[1].value }});
  loop: "{{ firefox_profiles | subelements('prefs', skip_missing=True) }}"

- name: Copy policies.json
  ansible.builtin.copy:
    src: firefox/policies.json
    dest: /usr/lib/firefox-esr/distribution/policies.json
    mode: "0444"

- name: Configure uBlock Origin
  ansible.builtin.template:
    src: firefox/uBlock0@raymondhill.net.json.j2
    dest: /home/{{ username }}/.mozilla/managed-storage/uBlock0@raymondhill.net.json
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0440"

- name: Ensures ~/.local/share/applications exists
  ansible.builtin.file:
    path: /home/{{ username }}/.local/share/applications
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Copy desktop files for profiles
  ansible.builtin.template:
    src: applications/firefox-desktop-file.desktop.j2
    dest: /home/{{ username }}/.local/share/applications/{{ item.name }}.desktop
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ firefox_profiles }}"

- name: Copy default desktop file
  ansible.builtin.copy:
    src: applications/firefox-esr.desktop
    dest: /home/{{ username }}/.local/share/applications/firefox-esr.desktop
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
