- name: Install Firefox
  apt:
    name: firefox-esr
    state: present
  tags:
    - dependencies

- name: Set Firefox as default browser
  alternatives:
    name: x-www-browser
    path: /usr/bin/firefox

- name: Ensures every profile dir exists
  file:
    path: "/home/{{ username }}/.mozilla/firefox/{{ item.name }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ firefox_profiles }}"

- name: Configure profiles.ini
  template:
    src: 'firefox/profiles.ini.j2'
    dest: "/home/{{ username }}/.mozilla/firefox/profiles.ini"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install ghacks-user.js for every profile
  get_url:
    url: "{{ ghacks_url }}"
    checksum: "{{ ghacks_checksum }}"
    dest: "/home/{{ username }}/.mozilla/firefox/{{ item.name }}/user.js"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ firefox_profiles }}"

- name: Configure firefox
  lineinfile:
    dest: "/home/{{ username }}/.mozilla/firefox/{{ item.0.name }}/user.js"
    regexp: '^user_pref\("{{ item.1.pref | regex_escape() }}",.*\)\;.*$'
    line: 'user_pref("{{ item.1.pref }}", {{ item.1.value }});'
  loop: "{{ firefox_profiles | subelements('prefs') }}"

- name: Copy policies.json
  copy:
    src: "firefox/policies.json"
    dest: "/usr/lib/firefox-esr/distribution/policies.json"

- name: Ensure ~/.mozilla/managed-storage exists
  file:
    path: "/home/{{ username }}/.mozilla/managed-storage"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure uBlock Origin
  template:
    src: "firefox/uBlock0@raymondhill.net.json.j2"
    dest: "/home/{{ username }}/.mozilla/managed-storage/uBlock0@raymondhill.net.json"
    owner: "{{ username }}"
    group: "{{ username }}"

# TODO
# Automatically install addons:
# https://addons.mozilla.org/en-US/firefox/addon/canvasblocker
# https://addons.mozilla.org/en-US/firefox/addon/https-everywhere/
# https://addons.mozilla.org/en-US/firefox/addon/clearurls/
# https://addons.mozilla.org/en-US/firefox/addon/privacy-pass/
# https://addons.mozilla.org/en-US/firefox/addon/smart-referer/
# https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/
# https://addons.mozilla.org/en-US/firefox/addon/css-exfil-protection/
# https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/
# https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/
# https://addons.mozilla.org/en-US/firefox/addon/dont-touch-my-tabs/
# https://github.com/Ibit-to/google-unlocked/releases/download/v1.5/google_unlocked-1.5.xpi
# https://github.com/iamadamdev/bypass-paywalls-firefox/releases/download/v1.6.3/bypass_paywalls-1.6.3-an+fx.xpi