- name: Install Firefox
  apt:
    name: firefox-esr
    state: present
  tags:
    - dependencies

- name: Set Firefox as default browser
  alternatives:
    name: x-www-browser
    path: /usr/bin/firefox

- name: Ensures every profile dir exists
  file:
    path: "/home/{{ username }}/.mozilla/firefox/{{ item.name }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ firefox_profiles }}"

- name: Configure profiles.ini
  template:
    src: 'firefox/profiles.ini.j2'
    dest: "/home/{{ username }}/.mozilla/firefox/profiles.ini"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install ghacks-user.js for every profile
  get_url:
    url: "{{ ghacks_url }}"
    checksum: "{{ ghacks_checksum }}"
    dest: "/home/{{ username }}/.mozilla/firefox/{{ item.name }}/user.js"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop: "{{ firefox_profiles }}"

- name: Configure firefox
  lineinfile:
    dest: "/home/{{ username }}/.mozilla/firefox/{{ item.0.name }}/user.js"
    regexp: '^user_pref\("{{ item.1.pref | regex_escape() }}",.*\)\;.*$'
    line: 'user_pref("{{ item.1.pref }}", {{ item.1.value }});'
  loop: "{{ firefox_profiles | subelements('prefs') }}"

- name: Copy policies.json
  copy:
    src: "firefox/policies.json"
    dest: "/usr/lib/firefox-esr/distribution/policies.json"

- name: Ensure ~/.mozilla/managed-storage exists
  file:
    path: "/home/{{ username }}/.mozilla/managed-storage"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure uBlock Origin
  template:
    src: "firefox/uBlock0@raymondhill.net.json.j2"
    dest: "/home/{{ username }}/.mozilla/managed-storage/uBlock0@raymondhill.net.json"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Ensure ~/.mozilla/native-messaging-hosts exists
  file:
    path: "/home/{{ username }}/.mozilla/native-messaging-hosts"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
