---
- name: Install flatpak
  register: install_flatpak
  until: install_flatpak is succeeded
  apt:
    name:
      - flatpak
      - flatpak-xdg-utils
      - xdg-desktop-portal
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-wlr
    state: present

- name: Ensures /etc/flatpak/remotes.d exists
  file:
    path: /etc/flatpak/remotes.d
    state: directory
    mode: 0755

- name: Copy flatpak remotes
  copy:
    src: flatpak/{{ item }}
    dest: /etc/flatpak/remotes.d/{{ item }}
    mode: 0744
  loop:
    - flathub.flatpakrepo
    - flathub-beta.flatpakrepo

- name: Add systemd service for auto updates
  copy:
    src: systemd/flatpak-update.{{ item }}
    dest: /home/{{ username }}/.config/systemd/user/flatpak-update.{{ item }}
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - service
    - timer

- name: Enable flatpak timer
  become: true
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: flatpak-update.timer
    enabled: true
    state: started

- name: Install themes for flatpak
  become: true
  become_user: "{{ username }}"
  flatpak:
    name: "{{ item }}"
    state: present
  loop:
    - "org.gtk.Gtk3theme.Adwaita-dark"
    - "org.kde.KStyle.Adwaita/{{ ansible_architecture }}/{{ kstyle_adwaita_version }}"
    - "org.kde.PlatformTheme.QGnomePlatform/{{ ansible_architecture }}/{{ qgnomeplatform_version }}"
