---
- name: Install flatpak
  register: install_flatpak
  until: install_flatpak is succeeded
  ansible.builtin.apt:
    name:
      - flatpak
      - flatpak-xdg-utils
    state: present

- name: Ensures /etc/flatpak/remotes.d exists
  ansible.builtin.file:
    path: /etc/flatpak/remotes.d
    state: directory
    mode: "0755"

- name: Copy flatpak remotes
  ansible.builtin.copy:
    src: flatpak/{{ item }}
    dest: /etc/flatpak/remotes.d/{{ item }}
    mode: "0744"
  loop:
    - flathub.flatpakrepo
    - flathub-beta.flatpakrepo
  register: flatpak_remotes
  notify:
    - Flatpak update

- name: Add systemd service for auto updates
  ansible.builtin.copy:
    src: systemd/flatpak-update.{{ item }}
    dest: /home/{{ username }}/.config/systemd/user/flatpak-update.{{ item }}
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - service
    - timer

- name: Enable flatpak timer
  become: true
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    scope: user
    name: flatpak-update.timer
    enabled: true
    state: started

- name: Install themes for flatpak
  become: true
  become_user: "{{ username }}"
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  register: flatpak_themes_install
  loop:
    - org.gtk.Gtk3theme.Adwaita-dark
    - org.kde.KStyle.Adwaita/{{ ansible_architecture }}/{{ kstyle_adwaita_version }}
    - org.kde.PlatformTheme.QGnomePlatform/{{ ansible_architecture }}/{{ qgnomeplatform_version }}
  changed_when: flatpak_themes_install.stdout | length > 0
