- name: Install gpg
  apt:
    name: gpg
    state: present

- name: Ensures ~/.gnupg exists
  file:
    path: "/home/{{ username }}/.gnupg"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy gpg config
  copy:
    src: 'gnupg/gpg.conf'
    dest: "/home/{{username}}/.gnupg/gpg.conf"
    mode: '0640'
    owner: "{{ username }}"
    group: "{{ username }}"
