---
- name: Install GraphicsMagick
  register: install_graphicsmagick
  until: install_graphicsmagick is succeeded
  ansible.builtin.apt:
    name:
      - graphicsmagick
      - graphicsmagick-imagemagick-compat
    state: present

# TODO re-enable
# - name: Configure GraphicsMagick delegates
#   copy:
#     src: GraphicsMagick/delegates.mgk
#     dest: /usr/lib/GraphicsMagick-1.4/config/delegates.mgk
#     mode: 0755
