---
- name: Create ipfs user
  user:
    name: ipfs
    shell: /bin/false
    create_home: true
    home: /var/lib/ipfs
    system: true
  register: ipfs_user

- name: Add subguid/subuids for user
  shell: usermod --add-subuids 100000-165535 --add-subgids 100000-165535 ipfs
  changed_when: false

- name: Run podman system migrate
  shell: podman system migrate
  changed_when: false

- name: Ensures required dirs exists
  file:
    path: /var/lib/ipfs/{{ item }}
    state: directory
    owner: ipfs
    group: ipfs
    mode: 0750
  loop:
    - export
    - data

- name: Create jackett container
  become: true
  become_user: ipfs
  containers.podman.podman_container:
    name: ipfs
    image: registry.hub.docker.com/ipfs/go-ipfs
    state: started
    expose:
      - 127.0.0.1:9117:9117
    volumes:
      - /etc/jackett:/config:rw
      - /var/lib/jackett:/downloads:rw
    generate_systemd:
      restart_policy: on-failure
