---
- name: Create ipfs user
  ansible.builtin.user:
    name: ipfs
    shell: /bin/false
    create_home: true
    home: /var/lib/ipfs
    system: true
  register: ipfs_user

- name: Ensures ipfs data dir exist
  ansible.builtin.file:
    path: "{{ large_dirs }}/ipfs"
    state: directory
    owner: ipfs
    group: ipfs
    mode: "0750"

- name: Ensures /var/lib/ipfs/.config/containers/systemd exists
  ansible.builtin.file:
    path: /var/lib/ipfs/.config/containers/systemd
    state: directory
    owner: ipfs
    group: ipfs
    mode: "0600"

- name: Copy ipfs container config
  ansible.builtin.copy:
    src: ipfs/ipfs.container
    dest: /var/lib/ipfs/.config/containers/systemd/ipfs.container
    mode: "0600"
    owner: ipfs
    group: ipfs
  register: ipfs_container
  notify:
    - Reload ipfs daemon

- name: Enable linger for ipfs user
  ansible.builtin.command:
    cmd: loginctl enable-linger ipfs
    creates: /var/lib/systemd/linger/ipfs

# - name: Enable ipfs
#   become: true
#   become_user: ipfs
#   ansible.builtin.systemd:
#     scope: user
#     name: ipfs
#     enabled: true
#     state: started
