- name: Create ipfs user
  user:
    name: ipfs
    shell: /bin/false
    create_home: yes
    home: /var/lib/ipfs
    system: yes

- name: Add subguid/subuids for user
  shell: usermod --add-subuids 100000-165535 --add-subgids 100000-165535 ipfs

- name: Run podman system migrate
  shell: podman system migrate

- name: Ensures required dirs exists
  file:
    path: "/var/lib/ipfs/{{ item }}"
    state: directory
    owner: "ipfs"
    group: "ipfs"
  loop:
    - export
    - data

- name: Pull ipfs image
  containers.podman.podman_image:
    name: registry.hub.docker.com/ipfs/go-ipfs

- name: Create ipfs container
  become: yes
  become_user: ipfs
  containers.podman.podman_container:
    name: ipfs
    image: registry.hub.docker.com/ipfs/go-ipfs
    state: present
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:5001:5001"
    volume:
      - '/var/lib/ipfs/export:/export'
      - '/var/lib/ipfs/data:/data/ipfs'

- name: Add systemd service
  copy:
    src: 'systemd/ipfs.service'
    dest: "/etc/systemd/system/ipfs.service"
    mode: '0640'

- name: Enable ipfs service
  systemd:
    name: ipfs
    enabled: yes
    state: started