---
- name: Create jackett user
  ansible.builtin.user:
    name: jackett
    shell: /bin/false
    create_home: true
    home: /var/lib/jackett
    system: true
  register: jackett_user

- name: Copy jackett container config
  ansible.builtin.copy:
    src: jackett/jackett.container
    dest: /var/lib/jackett/.config/containers/systemd/ipfs.container
    mode: "0600"
    owner: jackett
    group: jackett
  register: jackett_container

- name: Enable linger for jackett user
  ansible.builtin.command:
    cmd: loginctl enable-linger jackett
    creates: /var/lib/systemd/linger/jackett

- name: Ensures /etc/jackett exists
  ansible.builtin.file:
    path: /etc/jackett
    state: directory
    owner: jackett
    group: jackett
    mode: "0750"

- name: Copy jackett server config
  ansible.builtin.template:
    src: jackett/ServerConfig.json.j2
    dest: /etc/jackett/ServerConfig.json
    owner: jackett
    group: jackett
    mode: "0440"

- name: Create jackett container
  containers.podman.podman_container:
    name: jackett
    image: registry.hub.docker.com/linuxserver/jackett
    state: started
    subuidname: jackett
    publish:
      - 127.0.0.1:9117:9117
    volumes:
      - /etc/jackett:/config:rw
      - /var/lib/jackett:/downloads:rw
    generate_systemd:
      restart_policy: on-failure
