- name: Create jackett user
  user:
    name: jackett
    shell: /bin/false
    create_home: yes
    home: /var/lib/jackett
    system: yes

- name: Add subguid/subuids for user
  shell: usermod --add-subuids 100000-165535 --add-subgids 100000-165535 jackett

- name: Run podman system migrate
  shell: podman system migrate
  
- name: Ensures /etc/jackett exists
  file:
    path: "/etc/jackett"
    state: directory
    owner: "jackett"
    group: "jackett"

- name: Copy jackett server config
  template:
    src: 'jackett/ServerConfig.json.j2'
    dest: "/etc/jackett/ServerConfig.json"
    owner: jackett
    group: jackett

- name: Pull jackett image
  containers.podman.podman_image:
    name: registry.hub.docker.com/linuxserver/jackett

- name: Create jackett container
  become: yes
  become_user: jackett
  containers.podman.podman_container:
    name: jackett
    image: registry.hub.docker.com/linuxserver/jackett
    state: present
    ports:
      - "127.0.0.1:9117:9117"
    volume:
      - '/etc/jackett:/config:rw'
      - '/var/lib/jackett:/downloads:rw'

- name: Add systemd service
  copy:
    src: 'systemd/jackett.service'
    dest: "/etc/systemd/system/jackett.service"
    mode: '0640'

- name: Enable jackett service
  systemd:
    name: jackett
    enabled: yes
    state: started