- name: Install JOSM
  apt:
    name: josm
    state: present

- name: Ensures ~/.config/JOSM exists
  file:
    path: "/home/{{ username }}/.config/JOSM"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Write JOSM configuration
  template:
    src: 'JOSM/preferences.xml.j2'
    dest: "/home/{{ username }}/.config/JOSM/preferences.xml"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"
    force: no