---
- name: Install nheko
  register: install_nheko
  until: install_nheko is succeeded
  apt:
    name: nheko
    state: present

- name: Ensures ~/.config/nheko exists
  file:
    path: /home/{{ username }}/.config/nheko
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0750

- name: Configure nheko
  ini_file:
    path: /home/{{ username }}/.config/nheko/nheko.conf
    section: "{{ item[0] }}"
    option: "{{ item[1] }}"
    value: "{{ item[2] }}"
    create: true
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: 0440
  loop: "{{ nheko_options }}"
