- name: Install mpd, mpc, pms, and mpdris2
  apt:
    name:
      - mpd
      - mpc
      - pms
      - mpdris2
    state: present

- name: Ensures ~/.config/mpd exists
  file:
    path: "/home/{{ username }}/.config/mpd"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure mpd
  template:
    src: mpd/mpd.conf.j2
    dest: "/home/{{ username }}/.config/mpd/mpd.conf"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Disable mpd unit, we want to run it under user
  systemd:
    name: mpd
    enabled: no
    state: stopped