---
- name: Ensure nodejs and yarn is installed
  ansible.builtin.apt:
    name:
      - nodejs
      - yarn
    state: present

- name: Configure npm
  ansible.builtin.blockinfile:
    path: /home/{{ username }}/.npmrc
    create: true
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
    block: |
      prefix=~/.local
      fund=false
      send-metrics=false
      update-notifier=false
      audit=false
