- name: Install libreoffice packages and zathura
  apt:
    name:
      - libreoffice-writer
      - libreoffice-calc
      - libreoffice-impress
      - zathura
      - zathura-djvu
    state: present

- name: Download zaread
  get_url:
    url: "{{ zaread_url }}"
    dest: "/home/{{ username }}/.local/bin/zaread"
    checksum: "{{ zaread_checksum }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
