- name: Collect package facts
  package_facts:
    manager: auto

- name: Create temp dir for openbazaar
  tempfile:
    state: directory
  register: openbazaar_download_tempdir
  when: "('openbazaar2' not in ansible_facts.packages) or ('openbazaar2' in ansible_facts.packages and ansible_facts.packages.openbazaar2[0].version != openbazaar_version)"

- name: Get openbazaar
  get_url:
    url: "https://github.com/OpenBazaar/openbazaar-desktop/releases/download/v{{ openbazaar_version }}/openbazaar2_{{ openbazaar_version }}_amd64.deb"
    dest: "{{ openbazaar_download_tempdir.path }}/openbazaar.deb"
    checksum: "{{ openbazaar_checksum }}"
  when: "('openbazaar2' not in ansible_facts.packages) or ('openbazaar2' in ansible_facts.packages and ansible_facts.packages.openbazaar2[0].version != openbazaar_version)"

- name: Install openbazaar
  apt:
    deb: "{{ openbazaar_download_tempdir.path }}/openbazaar.deb"
  when: "('openbazaar2' not in ansible_facts.packages) or ('openbazaar2' in ansible_facts.packages and ansible_facts.packages.openbazaar2[0].version != openbazaar_version)"

- name: Remove tempdir
  file:
    path: "{{ openbazaar_download_tempdir.path }}"
    state: absent
  when: "('openbazaar2' not in ansible_facts.packages) or ('openbazaar2' in ansible_facts.packages and ansible_facts.packages.openbazaar2[0].version != openbazaar_version)"