---
- name: Install keepassxc
  register: install_keepassxc
  until: install_keepassxc is succeeded
  ansible.builtin.apt:
    name: keepassxc
    state: present

- name: Ensures ~/.config/keepassxc exists
  ansible.builtin.file:
    path: /home/{{ username }}/.config/keepassxc
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Configure keepassxc
  community.general.ini_file:
    path: /home/{{ username }}/.config/keepassxc/keepassxc.ini
    section: "{{ item[0] }}"
    option: "{{ item[1] }}"
    value: "{{ item[2] }}"
    create: true
    group: "{{ username }}"
    owner: "{{ username }}"
    mode: "0440"
  loop: "{{ keepassxc_options }}"
