- name: Install keepassxc
  apt:
    name: keepassxc
    state: present

- name: Ensures ~/.config/keepassxc exists
  file:
    path: "/home/{{ username }}/.config/keepassxc"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure keepassxc
  ini_file:
    path: "/home/{{ username }}/.config/keepassxc/keepassxc.ini"
    section: "{{ item[0] }}"
    option: "{{ item[1] }}"
    value: "{{ item[2] }}"
    create: yes
    group: "{{ username }}"
    owner: "{{ username }}"
  loop: "{{ keepassxc_options }}"