---
- name: Install pipx
  register: install_pipx
  until: install_pipx is succeeded
  apt:
    name: pipx
    state: present

- name: Ensures ~/.config/systemd/user exists
  file:
    path: /home/{{ username }}/.config/systemd/user
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0750

- name: Add systemd service for auto updates
  copy:
    src: systemd/pipx-upgrade.{{ item }}
    dest: /home/{{ username }}/.config/systemd/user/pipx-upgrade.{{ item }}
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - service
    - timer

- name: Enable pipx-upgrade timer
  become: true
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: pipx-upgrade.timer
    enabled: true
    state: started
