---
- name: Install podman and deps
  register: install_podman
  until: install_podman is succeeded
  apt:
    name:
      - podman
      - podman-docker
      - slirp4netns
      - rootlesskit
      - runsc
    state: present

- name: Enable docker.io registry
  lineinfile:
    path: /etc/containers/registries.conf
    regexp: ^unqualified-search-registries=
    line: unqualified-search-registries = ["docker.io"]

- name: Copy containers.conf
  copy:
    src: podman/containers.conf
    dest: /etc/containers/containers.conf
    mode: 0444

- name: Create nodocker
  file:
    path: /etc/containers/nodocker
    state: touch
    mode: 0444
