---
- name: Install privoxy
  register: install_privoxy
  until: install_privoxy is succeeded
  ansible.builtin.apt:
    name: privoxy
    state: present

- name: Configure privoxy
  ansible.builtin.copy:
    src: privoxy/config
    dest: /etc/privoxy/config
    mode: "0644"

- name: Configure user.action
  ansible.builtin.template:
    src: privoxy/user.action.j2
    dest: /etc/privoxy/user.action
    mode: "0644"

- name: Enable privoxy service
  ansible.builtin.systemd:
    name: privoxy
    state: started
    enabled: true
