- name: Install python-related packages
  apt:
    name:
      - python3
      - python3-pip
      - python3-setuptools
      #- python3-dev
      - python2
      - python-pip
      - python-setuptools
      - python2-dev
      - libpython2.7-dev
    state: present

# TODO implement some kind of unattended-upgrades
# for now debian pip version is broken
# https://github.com/pypa/pip/issues/5429
# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=912379

#- name: Install pipdate
#  pip:
#    name: pipdate
#    executable: pip3

#- name: Copy pipdate service
#  copy:
#    src: systemd/pipdate.service
#    dest: /etc/systemd/system/pipdate.service
#    mode: 0640

#- name: Copy pipdate timer
#  copy:
#    src: systemd/pipdate.timer
#    dest: /etc/systemd/system/pipdate.timer
#    mode: 0640

#- name: Enable pipdate timer
#  systemd:
#    name: pipdate.timer
#    state: started
#    enabled: yes