
- name: Install scrcpy
  apt:
    name:
      - scrcpy
      - adb
    state: present

- name: Ensures ~/.local/share/applications exists
  file:
    path: "/home/{{ username }}/.local/share/applications"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy desktop file
  copy:
    src: "applications/scrcpy.desktop"
    dest: "/home/{{ username }}/.local/share/applications/scrcpy.desktop"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"