---
- name: Install scrcpy
  register: install_scrcpy
  until: install_scrcpy is succeeded
  ansible.builtin.apt:
    name:
      - scrcpy
      - adb
    state: present

- name: Ensures ~/.local/share/applications exists
  ansible.builtin.file:
    path: /home/{{ username }}/.local/share/applications
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Copy desktop file
  ansible.builtin.copy:
    src: applications/scrcpy.desktop
    dest: /home/{{ username }}/.local/share/applications/scrcpy.desktop
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
