- name: Create searx user
  user:
    name: searx
    shell: /bin/false
    create_home: yes
    home: /var/lib/searx
    system: yes

- name: Add subguid/subuids for user
  shell: usermod --add-subuids 100000-165535 --add-subgids 100000-165535 searx

- name: Run podman system migrate
  shell: podman system migrate

- name: Pull searx image
  containers.podman.podman_image:
    name: registry.hub.docker.com/searx/searx

- name: Ensures /etc/searx exists
  file:
    path: "/etc/searx"
    state: directory
    owner: "searx"
    group: "searx"

- name: Copy searx config
  template:
    src: searx/settings.yml.j2
    dest: "/etc/searx/settings.yml"
    owner: "searx"
    group: "searx"

- name: Create searx container
  become: yes
  become_user: searx
  containers.podman.podman_container:
    name: searx
    image: registry.hub.docker.com/searx/searx
    state: present
    network: host
    env:
      BASE_URL: "http://localhost:8888/"
      BIND_ADDRESS: "127.0.0.1:8888"
    volume:
      - '/etc/searx:/etc/searx:ro'

- name: Add systemd service
  copy:
    src: 'systemd/searx.service'
    dest: "/etc/systemd/system/searx.service"
    mode: '0640'

- name: Enable searx service
  systemd:
    name: searx
    enabled: yes
    state: started