- name: Create searx user
  user:
    name: searx
    shell: /bin/false
    create_home: no
    system: yes

- name: Pull searx image
  containers.podman.podman_image:
    name: registry.hub.docker.com/searx/searx

- name: Ensures /etc/searx exists
  file:
    path: "/etc/searx"
    state: directory
    owner: "searx"
    group: "searx"

- name: Copy searx config
  template:
    src: searx/settings.yml.j2
    dest: "/etc/searx/settings.yml"
    owner: "searx"
    group: "searx"

- name: Run searx container
  containers.podman.podman_container:
    name: searx
    image: registry.hub.docker.com/searx/searx
    state: started
    ports:
      - "8888:8080"
    env:
      BASE_URL: "http://localhost:8888/"
    volume:
      - '/etc/searx:/etc/searx'

- name: Add systemd service
  template:
    src: 'systemd/searx.service.j2'
    dest: "/etc/systemd/system/searx.service"
    mode: '0640'

- name: Enable searx service
  systemd:
    name: searx
    enabled: yes
    state: started