---
- name: Create searx user
  user:
    name: searx
    shell: /bin/false
    create_home: true
    home: /var/lib/searx
    system: true
  register: searx_user

- name: Add subguid/subuids for user
  shell: usermod --add-subuids 100000-165535 --add-subgids 100000-165535 searx
  changed_when: false

- name: Run podman system migrate
  shell: podman system migrate
  changed_when: false

- name: Pull searx image
  containers.podman.podman_image:
    name: registry.hub.docker.com/searx/searx

- name: Ensures /etc/searx exists
  file:
    path: /etc/searx
    state: directory
    owner: searx
    group: searx
    mode: 0750

- name: Copy searx config
  template:
    src: searx/settings.yml.j2
    dest: /etc/searx/settings.yml
    mode: 0440
    owner: searx
    group: searx

- name: Add systemd service
  template:
    src: systemd/searx.service.j2
    dest: /etc/systemd/system/searx.service
    mode: "0640"

- name: Enable searx service
  systemd:
    name: searx
    enabled: true
    state: started
