- name: Install sia
  apt:
    name: sia
    state: present

- name: Ensures /var/lib/sia exists
  file:
    path: "/var/lib/sia"
    state: directory
    owner: sia

- name: Add systemd service
  copy:
    src: 'systemd/sia.service'
    dest: "/etc/systemd/system/sia.service"
    mode: '0640'
