- name: Download slack-term
  get_url:
    url: "https://github.com/erroneousboat/slack-term/releases/download/v{{ slackterm_version }}/slack-term-linux-amd64"
    dest: "/usr/local/bin/slack-term"
    checksum: "{{ slackterm_checksum }}"

- name: Add executable permission
  file:
    dest: /usr/local/bin/slack-term
    mode: 'a+x'