- name: Install Syncthing
  apt:
    name: syncthing
    state: present

- name: Ensures ~/.config/systemd/user exists
  file:
    path: "/home/{{ username }}/.config/systemd/user"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Add systemd service
  template:
    src: 'systemd/syncthing.service.j2'
    dest: "/home/{{ username }}/.config/systemd/user/syncthing.service"
    mode: '0640'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Check if config exists
  stat: 
    path: "/home/{{ username }}/.config/syncthing/config.xml"
  register: config_stat

- name: Restart Syncthing
  when: config_stat.stat.exists == False
  become: yes
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: syncthing
    state: restarted
    daemon_reload: yes

- name: Waiting for config
  when: config_stat.stat.exists == False
  wait_for:
    path: "/home/{{ username }}/.config/syncthing/config.xml"

- name: Configure syncthing
  xml:
    path: "/home/{{ username }}/.config/syncthing/config.xml"
    xpath: "{{ item.xpath }}"
    value: "{{ item.value }}"
  loop: 
    - xpath: '/configuration/gui/address'
      value: '127.0.0.1:8384'
    - xpath: '/configuration/options/globalAnnounceEnabled'
      value: 'false'
    - xpath: '/configuration/options/relaysEnabled'
      value: 'false'
    - xpath: '/configuration/options/natEnabled'
      value: 'false'
    - xpath: '/configuration/options/startBrowser'
      value: 'false'
    - xpath: '/configuration/gui/theme'
      value: 'black'
  register: syncthing_configure

- name: Restart Syncthing
  when: syncthing_configure.changed
  become: yes
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: syncthing
    state: restarted
    daemon_reload: yes

- name: Enable Syncthing service
  become: yes
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: syncthing
    enabled: yes