- name: Install foot
  package:
    name: foot
    state: present

- name: Ensures ~/.config/foot exists
  file:
    path: "/home/{{ username }}/.config/foot"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy foot config
  copy:
    src: foot/foot.ini
    dest: "/home/{{ username }}/.config/foot/foot.ini"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Set as default terminal emulator
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/footclient

- name: Add systemd user units
  copy:
    src: 'systemd/foot.service'
    dest: "/home/{{username}}/.config/systemd/user/foot.service"
    mode: '0640'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Enable systemd user services
  become: yes
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: "foot"
    enabled: yes
