---
- name: Install foot
  register: install_foot
  until: install_foot is succeeded
  ansible.builtin.package:
    name: foot
    state: present

- name: Ensures ~/.config/foot exists
  ansible.builtin.file:
    path: /home/{{ username }}/.config/foot
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Copy foot config
  ansible.builtin.copy:
    src: foot/foot.ini
    dest: /home/{{ username }}/.config/foot/foot.ini
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0440"

- name: Set as default terminal emulator
  community.general.alternatives:
    link: /usr/local/bin/x-terminal-emulator
    name: x-terminal-emulator
    path: /usr/bin/footclient
  failed_when: false

- name: Add systemd user units
  ansible.builtin.copy:
    src: systemd/foot.service
    dest: /home/{{ username }}/.config/systemd/user/foot.service
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Enable systemd user services
  become: true
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    scope: user
    name: foot
    enabled: true
