- name: Install rxvt-unicode
  package:
    name: rxvt-unicode
    state: present
  tags:
    - dependencies

- name: Set as default terminal emulator
  alternatives:
    name: x-terminal-emulator
    path: /usr/bin/urxvtc

- name: Configure urxvt
  blockinfile:
    path: /home/{{ username }}/.Xresources
    create: true
    marker: "! {mark} URXVT SETTINGS ANSIBLE MANAGED BLOCK"
    block: "{{ lookup('file', 'rxvt-xresources') }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0640