- name: Install mousepad
  apt:
    name: mousepad
    state: present

- name: Configure mousepad
  become: yes
  become_user: "{{ username }}"
  dconf:
    key: "/org/xfce/mousepad/preferences/{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - name: 'view/indent-width'
      value: '1'
    - name: 'view/highlight-current-line'
      value: "true"
    - name: 'view/word-wrap'
      value: "true"
    - name: 'view/show-right-margin'
      value: "true"
    - name: 'view/font-name'
      value: "'Hack 10'"
    - name: 'view/color-scheme'
      value: "'oblivion'"
    - name: 'view/show-line-numbers'
      value: "true"
    - name: 'view/insert-spaces'
      value: "true"
    - name: 'view/match-braces'
      value: "true"
    - name: 'view/indent-on-tab'
      value: "true"
    - name: 'view/right-margin-position'
      value: "80"
    - name: 'view/show-line-endings'
      value: "true"
    - name: 'view/show-whitespace'
      value: "true"
    - name: 'view/tab-width'
      value: "2"
    - name: "window/menubar-visible"
      value: "false"
    - name: "window/remember-state"
      value: "false"
    - name: "window/always-show-tabs"
      value: "false"
    - name: "window/statusbar-visible"
      value: "false"