- name: Install Tor
  apt:
    name:
      - tor
      - deb.torproject.org-keyring
      - torsocks
    state: present

- name: Generate tor hashed password
  become: yes
  become_user: "{{ username }}"
  shell: "tor --hash-password \"{{ lookup('password', 'credentials/tor_hashed length=15') }}\""
  register: tor_hashed_password

- name: Configure Tor
  template:
    src: 'tor/torrc.j2'
    dest: '/etc/tor/torrc'
    owner: 'debian-tor'
    group: 'debian-tor'
    mode: 0640
  register: torconfigure

- name: Enable Tor service
  systemd:
    name: tor@default
    enabled: yes

- name: Restart Tor
  when: torconfigure.changed
  systemd:
    name: tor@default
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: Check if tbb is already downloaded
  stat: 
    path: "/home/{{ username }}/.tb/tor-browser"
  register: tbb_exists

- name: Download tbb
  become: yes
  become_user: "{{ username }}"
  shell: "update-torbrowser --noask --ordinary"
  when: not tbb_exists.stat.exists

- name: Add systemd service for update-torbrowser
  copy:
    src: "systemd/update-torbrowser.{{ item }}"
    dest: "/home/{{username}}/.config/systemd/user/update-torbrowser.{{ item }}"
    mode: '0640'
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - 'service'
    - 'timer'

- name: Enable update-torbrowser timer
  become: yes
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: update-torbrowser.timer
    enabled: yes
    state: started

- name: Ensures ~/.local/share/applications exists
  file:
    path: "/home/{{ username }}/.local/share/applications"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy desktop file
  copy:
    src: "applications/janondisttorbrowser.desktop"
    dest: "/home/{{ username }}/.local/share/applications/janondisttorbrowser.desktop"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"