---
- name: Install mpv
  register: install_mpv
  until: install_mpv is succeeded
  ansible.builtin.apt:
    name: mpv
    state: present

- name: Install yt-dlp and streamlink
  ansible.builtin.apt:
    name:
      - yt-dlp
      - streamlink
    state: present

- name: Ensures ~/.config/streamlink exists
  ansible.builtin.file:
    path: /home/{{ username }}/.config/streamlink
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Configure streamlink
  ansible.builtin.copy:
    src: streamlink/config
    dest: /home/{{ username }}/.config/streamlink/config
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Ensures ~/.config/yt-dlp exists
  ansible.builtin.file:
    path: /home/{{ username }}/.config/yt-dlp
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Configure yt-dlp
  ansible.builtin.template:
    src: yt-dlp/config.j2
    dest: /home/{{ username }}/.config/yt-dlp/config
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Ensures ~/.config/mpv exists
  ansible.builtin.file:
    path: /home/{{ username }}/.config/mpv
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Configure mpv
  ansible.builtin.template:
    src: mpv/mpv.conf.j2
    dest: /home/{{ username }}/.config/mpv/mpv.conf
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
