---
- name: Install virt machine packages
  register: install_virt
  until: install_virt is succeeded
  ansible.builtin.apt:
    name:
      - vagrant
      - vagrant-cachier
      - vagrant-libvirt
      - vagrant-sshfs
      - virt-manager
      - libvirt-daemon-system
      - libvirt-clients
      - qemu-system
      - python3-psutil
      - dconf-cli
    state: present

- name: Configure virt-manager
  become: true
  become_user: "{{ username }}"
  community.general.dconf:
    key: /org/virt-manager/virt-manager/{{ item.name }}
    value: "{{ item.value }}"
    state: present
  loop:
    - name: urls/urls
      value: "['https://deb.debian.org/debian/dists/{{ ansible_distribution_release }}/main/installer-{{ architecture_map[ansible_architecture] }}/']"
