- name: Install tools to run vm
  apt:
    name: 
      - vagrant
      - vagrant-cachier
      - vagrant-libvirt
      - dnsmasq-base
      - gir1.2-spiceclientgtk-3.0
      - virtinst
      - libvirt-clients
      - libvirt-daemon-system
      - qemu-kvm
      - qemu-utils
      - virt-manager
      - libguestfs-tools
    state: present

- name: Install dconfs module deps
  apt:
    name:
      - python-psutil
      - dconf-cli
    state: present

- name: Configure virt-manager
  become: yes
  become_user: "{{ username }}"
  dconf:
    key: "/org/virt-manager/virt-manager/{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - name: "urls/urls"
      value: "['https://deb.debian.org/debian/dists/buster/main/installer-amd64/']"