---

- name: Install vscodium
  apt:
    name: codium
    state: latest

- name: Ensures ~/.config/VSCodium/User exists
  file:
    path: "/home/{{ username }}/.config/VSCodium/User"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy vscodium config
  copy:
    src: vscodium/settings.json
    dest: "/home/{{ username }}/.config/VSCodium/User/settings.json"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Find installed vscodium extensions
  become: yes
  become_user: "{{ username }}"
  shell: codium --list-extensions
  register: vscodium_installed_extensions_raw

- set_fact:
    vscodium_installed_extensions: "{{ (vscodium_installed_extensions_raw.stdout | lower).split('\n') }}"

- name: Install requested extensions
  become: yes
  become_user: "{{ username }}"
  shell: "codium --install-extension {{ item }} --force"
  when: item not in vscodium_installed_extensions
  loop: "{{ vscodium_extensions | map('lower') | list }}"
   