- name: Ensure amd64 enabled
  lineinfile:
    dest: /var/lib/dpkg/arch
    line: "amd64"
    create: yes

- name: Ensure i386 enabled
  lineinfile:
    dest: /var/lib/dpkg/arch
    line: "i386"
    create: yes
  register: i386_enabler

- name: Install wine
  apt:
    name: 
      - wine
      - wine64
      - fonts-wine
    update_cache: "{{ i386_enabler.changed }}"
    state: present