---
- name: Create temp dir for XD
  tempfile:
    state: directory
  register: xd_download_tempdir

- name: Download xd
  register: get_xd
  until: get_xd is succeeded
  get_url:
    url: https://github.com/majestrate/XD/releases/download/v{{ XD_version }}/XD-v{{ XD_version }}.tar.xz
    dest: "{{ xd_download_tempdir.path }}/xd.tar.xz"
    checksum: "{{ XD_checksum }}"
    mode: 0440

- name: Unarchive XD
  unarchive:
    src: "{{ xd_download_tempdir.path }}/xd.tar.xz"
    dest: "{{ xd_download_tempdir.path }}"
    remote_src: true

- name: Copy XD-i2p binary
  copy:
    src: "{{ xd_download_tempdir.path }}/XD-v{{ XD_version }}/XD-i2p-v{{ XD_version }}-linux-amd64"
    dest: /usr/local/bin/XD-i2p
    remote_src: true
    mode: 0755

- name: Copy XD-lokinet binary
  copy:
    src: "{{ xd_download_tempdir.path }}/XD-v{{ XD_version }}/XD-lokinet-v{{ XD_version }}-linux-amd64"
    dest: /usr/local/bin/XD-lokinet
    remote_src: true
    mode: 0755

- name: Remove tempdir
  file:
    path: "{{ xd_download_tempdir.path }}"
    state: absent

- name: Ensures XD dirs exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0750
  loop:
    - /home/{{ username }}/.config/XD
    - /home/{{ username }}/.cache/XD

- name: Copy XD config
  template:
    src: XD/torrents.ini.j2
    dest: /home/{{ username }}/.config/XD/torrents.ini
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0440

- name: Copy XD trackers list
  copy:
    src: XD/trackers.ini
    dest: /home/{{ username }}/.config/XD/trackers.ini
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0440

- name: Add systemd service
  template:
    src: systemd/XD-i2p.service.j2
    dest: /home/{{ username }}/.config/systemd/user/XD-i2p.service
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Enable XD-i2p service
  become: true
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: XD-i2p
    enabled: true
    state: started
