---
- name: Collect package facts
  package_facts:
    manager: auto

- name: Create temp dir for zecwallet
  tempfile:
    state: directory
  register: zecwallet_download_tempdir
  when: "'zecwallet-lite' not in ansible_facts.packages or ('zecwallet-lite' in ansible_facts.packages and ansible_facts.packages['zecwallet-lite'][0].version !=\
    \ zecwallet_lite_version)"

- name: Get ZecWallet Lite
  register: get_zecwallet
  until: get_zecwallet is succeeded
  get_url:
    url: https://github.com/adityapk00/zecwallet-lite/releases/download/v{{ zecwallet_lite_version }}/Zecwallet_Lite_{{ zecwallet_lite_version }}_amd64.deb
    dest: "{{ zecwallet_download_tempdir.path }}/zecwallet-lite.deb"
    checksum: "{{ zecwallet_lite_checksum }}"
    mode: 0440
  when: "'zecwallet-lite' not in ansible_facts.packages or ('zecwallet-lite' in ansible_facts.packages and ansible_facts.packages['zecwallet-lite'][0].version !=\
    \ zecwallet_lite_version)"

- name: Install ZecWallet Lite
  apt:
    deb: "{{ zecwallet_download_tempdir.path }}/zecwallet-lite.deb"
  when: "'zecwallet-lite' not in ansible_facts.packages or ('zecwallet-lite' in ansible_facts.packages and ansible_facts.packages['zecwallet-lite'][0].version !=\
    \ zecwallet_lite_version)"

- name: Remove tempdir
  file:
    path: "{{ zecwallet_download_tempdir.path }}"
    state: absent
  when: "'zecwallet-lite' not in ansible_facts.packages or ('zecwallet-lite' in ansible_facts.packages and ansible_facts.packages['zecwallet-lite'][0].version !=\
    \ zecwallet_lite_version)"
