---
- name: Ensures /usr/share/keyrings exists
  file:
    path: /usr/share/keyrings
    state: directory
    mode: 0755

- name: Copy gpg keys to /usr/share/keyrings
  copy:
    src: "{{ item }}"
    dest: /usr/share/keyrings/{{ item }}
    mode: 0444
  loop:
    - deb.nodesource.com-keyring.gpg
    - deb.torproject.org-keyring.gpg
    - dl.yarnpkg.com-keyring.gpg
    - repo.i2pd.xyz-keyring.gpg
    - vscodium-keyring.gpg
    - whonix.org-keyring.gpg
    - gvisor.gpg
    - deb.imaginary.stream-keyring.gpg
