- name: Set noatime for every fs
  mount:
    name: "{{ item.mount }}"
    src: "{{ item.device }}"
    fstype: "{{ item.fstype }}"
    opts: "{{ item.options }},noatime"
    state: present
  when: item.options.find(",") >= 0 and item.options.find("noatime") == -1
  with_items: "{{ ansible_mounts }}"
  