---
- name: Install 0 A.D.
  ansible.builtin.apt:
    name: 0ad
    state: present

- name: Ensures ~/.local/share/applications exists
  ansible.builtin.file:
    path: /home/{{ username }}/.local/share/applications
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Copy desktop file
  ansible.builtin.copy:
    src: applications/0ad.desktop
    dest: /home/{{ username }}/.local/share/applications/0ad.desktop
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
