---
- ansible.builtin.include_tasks: gamemode.yml
- ansible.builtin.include_tasks:
    file: pcsxr.yml
    apply:
      tags:
        - pcsxr
  tags:
    - always

- ansible.builtin.include_tasks:
    file: 0ad.yml
    apply:
      tags:
        - 0ad
  tags:
    - always

- ansible.builtin.include_tasks:
    file: openra.yml
    apply:
      tags:
        - openra
  tags:
    - always

- ansible.builtin.include_tasks:
    file: xonotic.yml
    apply:
      tags:
        - xonotic
  tags:
    - always

- ansible.builtin.include_tasks:
    file: taisei.yml
    apply:
      tags:
        - taisei
  tags:
    - always

- ansible.builtin.include_tasks:
    file: steam.yml
    apply:
      tags:
        - steam
  tags:
    - always
