---
- name: Install OpenRA from flatpak
  become: true
  become_user: "{{ username }}"
  community.general.flatpak:
    name: net.openra.OpenRA
    state: present

- name: Ensures ~/.local/share/applications exists
  ansible.builtin.file:
    path: /home/{{ username }}/.local/share/applications
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0755"

- name: Copy desktop file
  ansible.builtin.copy:
    src: applications/net.openra.OpenRA.desktop
    dest: /home/{{ username }}/.local/share/applications/net.openra.OpenRA.desktop
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
