- name: Install pcsxr
  apt:
    name: pcsxr
    state: present

- name: Ensures ~/.local/share/applications exists
  file:
    path: "/home/{{ username }}/.local/share/applications"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy desktop file
  copy:
    src: "applications/pcsxr.desktop"
    dest: "/home/{{ username }}/.local/share/applications/pcsxr.desktop"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"