---
- name: Install steam-devices
  register: install_steam_devices
  until: install_steam_devices is succeeded
  ansible.builtin.package:
    name: steam-devices
    state: present

- name: Install Steam from flatpak
  become: true
  become_user: "{{ username }}"
  register: install_steam
  until: install_steam is succeeded
  community.general.flatpak:
    name: com.valvesoftware.Steam
    state: present

- name: Ensures /var/lib/flatpak/overrides exists
  ansible.builtin.file:
    path: /var/lib/flatpak/overrides
    state: directory
    mode: "0555"

- name: Copy Steam overrides config
  ansible.builtin.copy:
    src: flatpak/overrides/com.valvesoftware.Steam
    dest: /var/lib/flatpak/overrides/com.valvesoftware.Steam
    mode: "0444"
