[parity]
base_path = "/home/openethereum"
auto_update = "none"
no_download = true

[rpc]
disable = false
port = 8545
interface = "local"
apis = ["all"]
cors = ["all"]

[websockets]
disable = false
port = 8546
interface = "local"
