- include_tasks: intel-video.yml
  when: thinkpad_x230|d(False) == True
- include_tasks: iwlwifi.yml
  when: thinkpad_x230|d(False) == True
- include_tasks: logitech-marble.yml
- include_tasks: nitrokey.yml
- include_tasks: onlykey.yml
- include_tasks: ledger.yml
- include_tasks: trezor.yml
- include_tasks: thinkfan.yml
  when: thinkpad_x230|d(False) == True
- include_tasks: tlp.yml
  when: thinkpad_x230|d(False) == True
- include_tasks: printer.yml
- include_tasks: nonfree_firmware.yml
  when: nonfree_firmware|d(False) == True