---
# - name: Install onlykey-agent
#   become: true
#   become_user: "{{ username }}"
#   shell: pipx install --force onlykey-agent
#   changed_when: false

- name: Collect package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Create temp dir for OnlyKey app
  ansible.builtin.tempfile:
    state: directory
  register: onlykey_download_tempdir
  when: ('onlykey' not in ansible_facts.packages) or ('onlykey' in ansible_facts.packages and ansible_facts.packages.onlykey[0].version != onlykey_version)

- name: Get onlykey
  ansible.builtin.get_url:
    url: https://github.com/trustcrypto/OnlyKey-App/releases/download/v{{ onlykey_version }}/OnlyKey_{{ onlykey_version }}_amd64.deb
    dest: "{{ onlykey_download_tempdir.path }}/onlykey.deb"
    checksum: "{{ onlykey_checksum }}"
    mode: "0444"
  when: ('onlykey' not in ansible_facts.packages) or ('onlykey' in ansible_facts.packages and ansible_facts.packages.onlykey[0].version != onlykey_version)

- name: Install onlykey
  ansible.builtin.apt:
    deb: "{{ onlykey_download_tempdir.path }}/onlykey.deb"
  when: ('onlykey' not in ansible_facts.packages) or ('onlykey' in ansible_facts.packages and ansible_facts.packages.onlykey[0].version != onlykey_version)

- name: Remove tempdir
  ansible.builtin.file:
    path: "{{ onlykey_download_tempdir.path }}"
    state: absent
  when: ('onlykey' not in ansible_facts.packages) or ('onlykey' in ansible_facts.packages and ansible_facts.packages.onlykey[0].version != onlykey_version)
