---
- name: Install cups, gutenprint driver and foomatic db
  register: install_cups
  until: install_cups is succeeded
  apt:
    name:
      - cups
      - printer-driver-gutenprint
      - foomatic-db-compressed-ppds
      - system-config-printer
    state: present

- name: Stop cups
  service:
    name: cups
    state: stopped

- name: Configure printers.conf
  template:
    src: cups/printers.conf.j2
    dest: /etc/cups/printers.conf
    mode: 0600
    owner: root
    group: lp

- name: Configure cupsd.conf
  copy:
    src: cups/cupsd.conf
    dest: /etc/cups/cupsd.conf
    mode: 0600
    owner: root
    group: lp

- name: Start cups
  service:
    name: cups
    state: started
