---
- name: Install cups, gutenprint driver and foomatic db
  register: install_cups
  until: install_cups is succeeded
  ansible.builtin.apt:
    name:
      - cups
      - printer-driver-gutenprint
      - foomatic-db-compressed-ppds
      - system-config-printer
    state: present

- name: Configure cupsd.conf
  ansible.builtin.copy:
    src: cups/cupsd.conf
    dest: /etc/cups/cupsd.conf
    mode: "0600"
    owner: root
    group: lp
