- name: Install sane and simple-scan
  apt:
    name:
      - sane-utils
      - simple-scan
    state: present
  tags:
    - dependencies

- name: Ensures /etc/sane.d exists
  file:
    path: "/etc/sane.d"
    state: directory
    owner: saned
    group: saned

- name: Configure sane
  template:
    src: 'sane.d/net.conf.j2'
    dest: "/etc/sane.d/net.conf"
    mode: '0640'
    owner: saned
    group: saned
