---
- name: Install thinkfan
  register: install_thinkfan
  until: install_thinkfan is succeeded
  package:
    name: thinkfan
    state: present

- name: Add module
  modprobe:
    name: thinkpad_acpi
    params: fan_control=1
    state: present
  # TODO proper detection when we need to load module
  # currently it fails in vagrant
  failed_when: false
