---
- name: Install tlp
  register: install_tlp
  until: install_tlp is succeeded
  ansible.builtin.apt:
    name:
      - tlp
      - tlp-rdw
      - smartmontools
      - linux-cpupower
      - powermgmt-base
      - ethtool
    state: present

- name: Set tlp params
  ansible.builtin.copy:
    src: tlp/00-optimize.conf
    dest: /etc/tlp.d/00-optimize.conf
    mode: "0640"
