- name: Install linux headers
  apt:
    name: "linux-headers-{{ ansible_kernel }}"
    state: present

- name: Install tlp
  apt:
    name:
      - acpi-call-dkms
      - tlp
      - tlp-rdw
    state: present
  tags:
    - dependencies

- name: Set START_CHARGE_THRESH_BAT0
  lineinfile:
    path: /etc/default/tlp
    regexp: '^START_CHARGE_THRESH_BAT0='
    line: START_CHARGE_THRESH_BAT0=67

- name: Set STOP_CHARGE_THRESH_BAT0
  lineinfile:
    path: /etc/default/tlp
    regexp: '^STOP_CHARGE_THRESH_BAT0='
    line: STOP_CHARGE_THRESH_BAT0=100