---
- name: Install trezor package
  register: install_trezor
  until: install_trezor is succeeded
  apt:
    name: trezor
    state: present

- name: Install trezor_agent
  become: true
  become_user: "{{ username }}"
  shell: pipx install --force trezor_agent
  changed_when: true
