---
- name: Install vulkan deps
  register: install_vulkan
  until: install_vulkan is succeeded
  apt:
    name:
      - mesa-vulkan-drivers
      - libvulkan1
      - vulkan-validationlayers
    state: present
