---
- name: Remove pulseaudio
  ansible.builtin.apt:
    name: pulseaudio
    state: absent

- name: Install pipewire and openal
  ansible.builtin.apt:
    name:
      - libopenal1
      - pipewire
      - wireplumber
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack
      - pulseaudio-utils
    state: present

- name: Ensures /etc/pipewire exists
  ansible.builtin.file:
    path: /etc/pipewire
    state: directory
    mode: "0660"

- name: Copy pipewire configs
  ansible.builtin.copy:
    src: pipewire/{{ item }}
    dest: /etc/pipewire/{{ item }}
    mode: "0444"
  loop:
    - pipewire.conf
    - pipewire-pulse.conf

- name: Enable wireplumber service
  become: true
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    scope: user
    name: wireplumber
    enabled: true
