- name: Install pulseaudio, openal and pipewire
  apt:
    name:
      - pulseaudio
      - pulseaudio-utils
      - libopenal1
      - pipewire
    state: present

- name: Configure pulseaudio
  copy:
    src: "{{ item }}"
    dest: "/etc/pulse/{{ item }}"
  loop:
   - daemon.conf
   - default.pa