- name: Remove pulseaudio
  apt:
    name: pulseaudio
    state: absent

- name: Install pipewire and openal
  apt:
    name:
      - libopenal1
      - pipewire
      - wireplumber
      - pipewire-pulse
      - pipewire-alsa
      - pipewire-jack
      - pulseaudio-utils
    state: present