---
- include_tasks:
    file: nftables.yml
    apply:
      tags:
        - nftables
  tags:
    - always
- include_tasks:
    file: opensnitch.yml
    apply:
      tags:
        - opensnitch
  tags:
    - always
