---
- name: Install nftables
  register: install_nftables
  until: install_nftables is succeeded
  apt:
    name: nftables
    state: present

- name: Configure nftables
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: 0640

- name: Enable nftables service
  systemd:
    name: nftables
    enabled: true
    state: started
