---
- name: Install nftables
  register: install_nftables
  until: install_nftables is succeeded
  ansible.builtin.apt:
    name: nftables
    state: present

- name: Configure nftables
  ansible.builtin.template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    mode: "0640"

- name: Enable nftables service
  ansible.builtin.systemd:
    name: nftables
    enabled: true
    state: started
