---
- name: Install opensnitch
  register: install_opensnitch
  until: install_opensnitch is succeeded
  ansible.builtin.apt:
    name:
      - opensnitch
      - python3-opensnitch-ui
    state: present

- name: Configure opensnitch
  ansible.builtin.copy:
    src: opensnitch/default-config.json
    dest: /etc/opensnitchd/default-config.json
    mode: "0644"

- name: Copy opensnitch rules
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: /etc/opensnitchd/rules/{{ item.path | splitext | first }}
    mode: "0644"
  with_community.general.filetree: templates/opensnitch/rules/
  when: item.state == 'file'
