---
- name: Install deps
  register: install_opensnitch_deps
  until: install_opensnitch_deps is succeeded
  apt:
    name:
      - libnetfilter-queue1
      - libc6
      - libnfnetlink0
      - debconf
      - libqt5sql5-sqlite
      - python3-six
      - python3-pyqt5
      - python3-pyqt5.qtsql
      - python3-pyinotify
      - python3-notify2
      - whiptail
      - python3-grpcio
      - python3-protobuf
      - python3-slugify
      - python3-unidecode
    state: present

- name: Collect package facts
  package_facts:
    manager: auto

- name: Create temp dir for opensnitch
  tempfile:
    state: directory
  register: opensnitch_download_tempdir
  when: ('opensnitch' not in ansible_facts.packages) or ('opensnitch' in ansible_facts.packages and ansible_facts.packages.opensnitch[0].version != opensnitch_version)

- name: Get opensnitch
  register: get_opensnitch
  until: get_opensnitch is succeeded
  get_url:
    url: "{{ opensnitch_link }}"
    dest: "{{ opensnitch_download_tempdir.path }}/opensnitch.deb"
    checksum: "{{ opensnitch_checksum }}"
    mode: 0555
  when: ('opensnitch' not in ansible_facts.packages) or ('opensnitch' in ansible_facts.packages and ansible_facts.packages.opensnitch[0].version != opensnitch_version)

- name: Get opensnitch ui
  register: get_opensnitch_ui
  until: get_opensnitch_ui is succeeded
  get_url:
    url: "{{ opensnitch_ui_link }}"
    dest: "{{ opensnitch_download_tempdir.path }}/python3-opensnitch-ui.deb"
    checksum: "{{ opensnitch_ui_checksum }}"
    mode: 0555
  when: ('python3-opensnitch-ui' not in ansible_facts.packages) or ('python3-opensnitch-ui' in ansible_facts.packages and ansible_facts.packages['python3-opensnitch-ui'][0].version
    != opensnitch_version)

- name: Install opensnitch ui
  apt:
    deb: "{{ opensnitch_download_tempdir.path }}/python3-opensnitch-ui.deb"
  when: ('python3-opensnitch-ui' not in ansible_facts.packages) or ('python3-opensnitch-ui' in ansible_facts.packages and ansible_facts.packages['python3-opensnitch-ui'][0].version
    != opensnitch_version)

- name: Install opensnitch
  apt:
    deb: "{{ opensnitch_download_tempdir.path }}/opensnitch.deb"
  when: ('opensnitch' not in ansible_facts.packages) or ('opensnitch' in ansible_facts.packages and ansible_facts.packages.opensnitch[0].version != opensnitch_version)

- name: Remove tempdir
  file:
    path: "{{ opensnitch_download_tempdir.path }}"
    state: absent
  when: ('opensnitch' not in ansible_facts.packages) or ('opensnitch' in ansible_facts.packages and ansible_facts.packages.opensnitch[0].version != opensnitch_version)

- name: Configure opensnitch
  copy:
    src: opensnitch/default-config.json
    dest: /etc/opensnitchd/default-config.json
    mode: 0644

- name: Copy opensnitch rules
  template:
    src: "{{ item.src }}"
    dest: "/etc/opensnitchd/rules/{{ item.path | splitext | first }}"
    mode: 0644
  with_community.general.filetree: "templates/opensnitch/rules/"
  when: item.state == 'file'
