---
- name: Install Tor and apt-transport-tor
  register: install_apt_transport_tor
  until: install_apt_transport_tor is succeeded
  apt:
    name:
      - tor
      - apt-transport-tor

# - name: Find list of repos
#   find:
#     paths: /etc/apt/sources.list.d
#     recurse: false
#     file_type: file
#     patterns: "*.list"
#   register: sources_list

# - name: Comment out all the unneded repos
#   replace:
#     dest: "{{ item }}"
#     regexp: ^(deb-src|deb) https?:\/\/.*\.debian\.org.*$
#     replace: "# \\1"
#   loop: "{{ sources_list.files | map(attribute='path') | list + ['/etc/apt/sources.list'] }}"

# - name: Use apt-transport-tor for other repos
#   replace:
#     dest: "{{ item }}"
#     regexp: ^(deb|deb-src) (https?:\/\/.*)$
#     replace: \1 tor+\2
#   loop: "{{ sources_list.files | map(attribute='path') | list + ['/etc/apt/sources.list'] }}"
