---
- name: Install Tor and apt-transport-tor
  apt:
    name:
      - tor
      - apt-transport-tor
  tags:
    - dependencies

- name: Find list of repos
  find:
    paths: /etc/apt/sources.list.d
    recurse: no
    file_type: file
    patterns: '*.list'
  register: sources_list

- name: Comment out all the unneded repos
  replace:
    dest: "{{ item }}"
    regexp: '^(deb-src|deb) https?:\/\/.*\.debian\.org.*$'
    replace: '# \1'
  loop: "{{ sources_list.files | map(attribute='path') | list + ['/etc/apt/sources.list'] }}"

- name: Use apt-transport-tor for other repos
  replace:
    dest: "{{ item }}"
    regexp: '^(deb|deb-src) (https?:\/\/.*)$'
    replace: '\1 tor+\2'
  loop: "{{ sources_list.files | map(attribute='path') | list + ['/etc/apt/sources.list'] }}"
  when:
    - item is not match('.*https:\/\/gitlab\.com/.*')
    - item is not match('.*https:\/\/apt\.qm64\.tech/.*')