---
- name: Converge
  become: true
  hosts: all
  vars:
    provided_username: vagrant
  tasks:
    - name: Ensure /etc/polkit-1/rules.d exists
      file:
        path: /etc/polkit-1/rules.d
        state: directory
    - name: Copy flatpak polkit rule
      copy:
        src: org.freedesktop.Flatpak.rules
        dest: /etc/polkit-1/rules.d/org.freedesktop.Flatpak.rules
        mode: 0744
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install deps
      apt:
        name:
          - python3-jmespath
          - python3-passlib
          - python3-lxml
          - git
          - python-is-python3
        state: present
- import_playbook: ../../main.yml