---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
  cachier: machine
  provision: no
  parallel: true
  default_box: debian/bookworm64
#  name: podman
platforms:
  - name: debian
    box: debian/bookworm64
    memory: 4096
    cpus: 2
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
  inventory:
    host_vars:
      debian:
        username: vagrant

verifier:
  name: ansible
lint: |
  set -e
  yamllint roles *.yml
  ansible-lint -p main.yml roles
