- name: Add startx to ~/.profile
  blockinfile:
    path: /home/{{ username }}/.profile
    mode: 0755
    create: true
    owner: "{{ username }}"
    group: "{{ username }}"
    block: |
      if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
        exec startx
      fi

- name: Ensures /etc/systemd/system/getty@tty1.service.d exists
  file:
    path: "/etc/systemd/system/getty@tty1.service.d"
    state: directory

- name: Enable autologin on tty1
  template:
    src: 'systemd/override.conf.j2'
    dest: '/etc/systemd/system/getty@tty1.service.d/override.conf'
    mode: 0644