- name: Add sway to ~/.profile
  blockinfile:
    path: /home/{{ username }}/.profile
    mode: 0755
    create: true
    owner: "{{ username }}"
    group: "{{ username }}"
    block: |
      TERM=xterm
      NODE_OPTIONS=--max_old_space_size=8192
      _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=gasp -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Djdk.gtk.version=3'
      _JAVA_AWT_WM_NONREPARENTING=1
      GTK2_RC_FILES="$HOME/.gtkrc-2.0"
      CLUTTER_BACKEND=wayland
      SDL_VIDEDRIVER=wayland
      XDG_SESSION_TYPE=wayland
      XDG_CURRENT_DESKTOP="sway"
      QT_QPA_PLATFORMTHEME=qt5ct
      QT_QPA_PLATFORM=wayland
      QT_WAYLAND_DISABLE_WINDOWDECORATION=1
      SAL_USE_VCLPLUGIN=gtk3
      if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
        exec sway
      fi

- name: Ensures /etc/systemd/system/getty@tty1.service.d exists
  file:
    path: "/etc/systemd/system/getty@tty1.service.d"
    state: directory

- name: Enable autologin on tty1
  template:
    src: 'systemd/override.conf.j2'
    dest: '/etc/systemd/system/getty@tty1.service.d/override.conf'
    mode: 0644