---
- name: Add sway to ~/.profile
  blockinfile:
    path: /home/{{ username }}/.profile
    mode: 0755
    create: true
    owner: "{{ username }}"
    group: "{{ username }}"
    block: |
      while read -r l; do
        eval export $l
      done < <(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)
      if [ -z $DISPLAY ] && [ "$(tty)" = "/dev/tty1" ]; then
        exec sway
      fi

- name: Ensures /etc/systemd/system/getty@tty1.service.d exists
  file:
    path: /etc/systemd/system/getty@tty1.service.d
    state: directory
    mode: 0755

- name: Enable autologin on tty1
  template:
    src: systemd/override.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
    mode: 0644
