- name: Install wofi
  apt:
    name: wofi
    state: present

- name: Ensures ~/.config/wofi exists
  file:
    path: "/home/{{ username }}/.config/wofi"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy wofi config
  copy:
    src: wofi/config
    dest: "/home/{{ username }}/.config/wofi/config"
    owner: "{{ username }}"
    group: "{{ username }}"
