- name: Install rofi
  apt:
    name: rofi
    state: present

- name: Ensures ~/.config/rofi exists
  file:
    path: "/home/{{ username }}/.config/rofi"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy rofi config
  copy:
    src: rofi/config
    dest: "/home/{{ username }}/.config/rofi/config"
    owner: "{{ username }}"
    group: "{{ username }}"
