- name: Ensures ~/.config/autostart exists
  file:
    path: "/home/{{ username }}/.config/autostart"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Symlink some desktop files to autostart
  file:
    src: "{{ item.location }}/{{ item.name }}.desktop"
    dest: "/home/{{ username }}/.config/autostart/{{ item.name }}.desktop"
    state: link
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - location: "/usr/share/applications"
      name: org.keepassxc.KeePassXC
    - location: "/usr/share/applications"
      name: telegramdesktop