- name: Ensures ~/.config/autostart exists
  file:
    path: "/home/{{ username }}/.config/autostart"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Symlink some desktop files to autostart
  file:
    src: "{{ item.location }}/{{ item.name }}.desktop"
    dest: "/home/{{ username }}/.config/autostart/{{ item.name }}.desktop"
    state: link
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - location: "/usr/share/applications"
      name: org.keepassxc.KeePassXC
    - location: "/usr/share/applications"
      name: telegramdesktop
    - location: "/home/{{ username }}/.local/share/applications"
      name: thunderbird
    - location: "/home/{{ username }}/.local/share/applications"
      name: firefox-esr
    - location: "/home/{{ username }}/.local/share/applications"
      name: codium

- name: Add dex systemd user units
  copy:
    src: 'systemd/dex.service'
    dest: "/home/{{username}}/.config/systemd/user/dex.service"
    mode: '0640'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Enable dex systemd user services
  become: yes
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: dex
    enabled: yes