- name: Ensures ~/.config/autostart exists
  file:
    path: "/home/{{ username }}/.config/autostart"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy autostart files
  copy:
    src: autostart/{{ item }}.desktop
    dest: "/home/{{ username }}/.config/autostart/{{ item }}.desktop"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - foot

- name: Symlink some desktop files to autostart
  file:
    src: "/usr/share/applications/{{ item }}.desktop"
    dest: "/home/{{ username }}/.config/autostart/{{ item }}.desktop"
    state: link
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - "org.keepassxc.KeePassXC"
    - "telegramdesktop"
    - "firefox-esr"
    - "thunderbird"
    - "codium"