- name: Install conky
  apt:
    name: conky
    state: present

- name: Ensures ~/.config/conky exists
  file:
    path: "/home/{{ username }}/.config/conky"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy conky.conf
  copy:
    src: conky/conky.conf
    dest: "/home/{{ username }}/.config/conky/conky.conf"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Ensures ~/.config/autostart exists
  file:
    path: "/home/{{ username }}/.config/autostart"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy conky autostart file
  copy:
    src: autostart/conky.desktop
    dest: "/home/{{ username }}/.config/autostart/conky.desktop"
    owner: "{{ username }}"
    group: "{{ username }}"