- name: Install other gooodies
  apt:
    name:
      - brightnessctl
      - brightness-udev
      - network-manager-gnome
      - xdg-user-dirs
      - dex
      - kanshi
      - ffmpegthumbnailer
      - tumbler
      - playerctl
      - tb-starter
      - tb-updater
      - grim
      - slurp
      - wl-clipboard
      - swaybg
      - qtwayland5
      - xwayland
    state: present

- name: Ensures ~/.config exists
  file:
    path: "/home/{{ username }}/.config"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure user dirs
  template:
    src: 'user-dirs.dirs.j2'
    dest: "/home/{{ username }}/.config/user-dirs.dirs"
    mode: 0760
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Ensures ~/.config/gtk-3.0 exists
  file:
    path: "/home/{{ username }}/.config/gtk-3.0"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure bookmarks
  template:
    src: 'bookmarks.j2'
    dest: "/home/{{ username }}/.config/gtk-3.0/bookmarks"
    mode: 0660
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install dconfs module deps
  apt:
    name:
      - python3-psutil
      - dconf-cli
    state: present

- name: Configure file-chooser
  become: yes
  become_user: "{{ username }}"
  dconf:
    key: "/org/gtk/settings/file-chooser/{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - name: "location-mode"
      value: "'filename-entry'"
    - name: "sort-directories-first"
      value: "true"
    - name: "startup-mode"
      value: "'cwd'"

- name: Configure nm-applet
  become: yes
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/nm-applet/{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - name: "suppress-wireless-networks-available"
      value: "true"
    - name: "disable-connected-notification"
      value: "true"

- name: Configure other dconf settings
  become: yes
  become_user: "{{ username }}"
  dconf:
    key: "/org/gnome/desktop/{{ item.name }}"
    value: "{{ item.value }}"
    state: present
  loop:
    - name: "privacy/hide-identity"
      value: "true"
    - name: "privacy/show-full-name-in-top-bar"
      value: "false"
    - name: "privacy/remember-recent-files"
      value: "false"
    - name: "privacy/remember-app-usage"
      value: "false"
    - name: "privacy/old-files-age"
      value: "5"
    - name: "thumbnail_cache/maximum_age"
      value: "5"
    - name: "media-handling/automount-open"
      value: "false"
    - name: "media-handling/autorun-never"
      value: "true"

- name: Ensures /usr/lib/environment.d exists
  file:
    path: "/usr/lib/environment.d"
    state: directory

- name: Configure env
  copy:
    src: "environment.d/{{ item }}.conf"
    dest: "/usr/lib/environment.d/{{ item }}.conf"
    mode: 0666
  loop:
    - basic
    - adblock
    - optout

- name: Add kanshi systemd user unit
  copy:
    src: 'systemd/kanshi.service'
    dest: "/home/{{username}}/.config/systemd/user/kanshi.service"
    mode: '0640'
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Enable kanshi systemd user service
  become: yes
  become_user: "{{ username }}"
  systemd:
    scope: user
    name: "kanshi"
    enabled: yes