- include_tasks: screenlock.yml
- include_tasks: conky.yml
  when: thinkpad_x230|d(False) == True
- include_tasks: awesome.yml
- include_tasks: jaro.yml
- include_tasks: goodies.yml
- include_tasks: batify.yml
  when: thinkpad_x230|d(False) == True