- include_tasks: screenlock.yml
- include_tasks: statusbar.yml
- include_tasks: application-launcher.yml
- include_tasks: uri-opener.yml
- include_tasks: window-manager.yml
- include_tasks: goodies.yml
- include_tasks: autostart.yml
- include_tasks: batify.yml
  when: thinkpad_x230|d(False) == True