---
- include_tasks: doas.yml
- include_tasks:
    file: oom.yml
    apply:
      tags:
        - optimizations
        - oomd
  tags:
    - always
- include_tasks:
    file: screenlock.yml
    apply:
      tags:
        - screenlock
  tags:
    - always
- include_tasks:
    file: statusbar.yml
    apply:
      tags:
        - statusbar
  tags:
    - always
- include_tasks:
    file: application-launcher.yml
    apply:
      tags:
        - application-launcher
  tags:
    - always
- include_tasks:
    file: uri-opener.yml
    apply:
      tags:
        - uri-opener
  tags:
    - always
- include_tasks:
    file: window-manager.yml
    apply:
      tags:
        - window-manager
        - sway
  tags:
    - always
- include_tasks: goodies.yml
- include_tasks:
    file: autostart.yml
    apply:
      tags:
        - autostart
  tags:
    - always
- include_tasks:
    file: autonice.yml
    apply:
      tags:
        - autonice
        - ananicy
  tags:
    - always
- include_tasks:
    file: notifications.yml
    apply:
      tags:
        - notifications
  tags:
    - always
- include_tasks:
    file: cfs-zen-tweaks.yml
    apply:
      tags:
        - optimizations
  tags:
    - always
