---
- name: Install mako
  register: install_mako
  until: install_mako is succeeded
  ansible.builtin.apt:
    name: mako-notifier
    state: present

- name: Ensures ~/.config/mako exists
  ansible.builtin.file:
    path: /home/{{ username }}/.config/mako
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Copy mako config
  ansible.builtin.copy:
    src: mako/config
    dest: /home/{{ username }}/.config/mako/config
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0440"

- name: Add mako systemd user unit
  ansible.builtin.copy:
    src: systemd/mako.service
    dest: /home/{{ username }}/.config/systemd/user/mako.service
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Enable mako systemd user service
  become: true
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    scope: user
    name: mako
    enabled: true
