---
- name: Install oomd
  register: install_oomd
  until: install_oomd is succeeded
  apt:
    name: oomd
    state: present

- name: Enable required accounting settings
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: ^{{ item }}=
    line: "{{ item }}=true"
  loop:
    - DefaultCPUAccounting
    - DefaultIOAccounting
    - DefaultMemoryAccounting
    - DefaultTasksAccounting
