---
- name: Install waybar and deps
  register: install_waybar
  until: install_waybar is succeeded
  ansible.builtin.apt:
    name:
      - waybar
    state: present

- name: Ensures ~/.config/waybar exists
  ansible.builtin.file:
    path: /home/{{ username }}/.config/waybar
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Configure waybar
  ansible.builtin.copy:
    src: waybar/{{ item }}
    dest: /home/{{ username }}/.config/waybar/{{ item }}
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0440"
  loop:
    - config
    - style.css

- name: Enable waybar systemd user service
  become: true
  become_user: "{{ username }}"
  ansible.builtin.systemd:
    scope: user
    name: waybar
    enabled: true
