- name: Install waybar and deps
  apt:
    name:
      - waybar
      - gsimplecal
    state: present

- name: Ensures ~/.config/gsimplecal exists
  file:
    path: "/home/{{ username }}/.config/gsimplecal"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy gsimplecal config
  copy:
    src: gsimplecal/config
    dest: "/home/{{ username }}/.config/gsimplecal/config"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Ensures ~/.config/waybar exists
  file:
    path: "/home/{{ username }}/.config/waybar"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Configure waybar
  copy:
    src: "waybar/{{ item }}"
    dest: "/home/{{ username }}/.config/waybar/{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
  loop:
    - 'config'
    - 'style.css'
    - 'microphone.sh'

- name: Add executable for microphone.sh
  file:
    dest: "/home/{{ username }}/.config/waybar/microphone.sh"
    mode: 'a+x'