---
- name: Install sway
  register: install_sway
  until: install_sway is succeeded
  ansible.builtin.apt:
    name: sway
    state: present

- name: Ensures ~/.config/sway exists
  ansible.builtin.file:
    path: /home/{{ username }}/.config/sway
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Copy sway config
  ansible.builtin.copy:
    src: sway/config
    dest: /home/{{ username }}/.config/sway/config
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0440"

- name: Ensures ~/.config/systemd/user exists
  ansible.builtin.file:
    path: /home/{{ username }}/.config/systemd/user
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0750"

- name: Add sway-session.target
  ansible.builtin.copy:
    src: systemd/sway-session.target
    dest: /home/{{ username }}/.config/systemd/user/sway-session.target
    mode: "0640"
    owner: "{{ username }}"
    group: "{{ username }}"
