- name: Install sway
  apt:
    name: sway
    state: present

- name: Ensures ~/.config/sway exists
  file:
    path: "/home/{{ username }}/.config/sway"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Copy sway config
  copy:
    src: sway/config
    dest: "/home/{{ username }}/.config/sway/config"
    owner: "{{ username }}"
    group: "{{ username }}"
