---
- name: Configure apparmor
  ansible.builtin.lineinfile:
    path: /etc/apparmor/parser.conf
    line: "{{ item }}"
  loop:
    - quiet
    - write-cache
    - cache-loc /etc/apparmor/earlypolicy/

# - name: Create apparmor-even-more-profiles tempdir
#   ansible.builtin.tempfile:
#     state: directory
#   register: apparmor_profiles_tempdir

# - name: Clone apparmor-even-more-profiles repo
#   ansible.builtin.git:
#     repo: https://github.com/komachi/apparmor-even-more-profiles.git
#     dest: "{{ apparmor_profiles_tempdir.path }}"
#     recursive: true
#     clone: true
#     version: "{{ apparmor_even_more_profiles_commit }}"

# - name: Copy profiles
#   ansible.builtin.copy:
#     src: "{{ apparmor_profiles_tempdir.path }}/profiles/"
#     dest: /etc/apparmor.d/
#     remote_src: true
#     follow: true
#     force: true
#     mode: "0440"
#   register: apparmorprofilescopy
#   notify:
#     - Reload apparmor

# - name: Read extra profiles file
#   ansible.builtin.slurp:
#     src: "{{ apparmor_profiles_tempdir.path }}/extra_profiles.list"
#   register: extra_apparmor_profiles

- name: Ensure additional apparmor profiles packages is present
  ansible.builtin.apt:
    name:
      - apparmor-profiles
      - apparmor-profiles-extra
    state: present

# - name: Symlink extra profiles
#   ansible.builtin.file:
#     src: /usr/share/apparmor/extra-profiles/{{ item }}
#     dest: /etc/apparmor.d/{{ item }}
#     state: link
#   when: item | length > 0
#   loop: "{{ (extra_apparmor_profiles.content | b64decode).split('\n') }}"
#   register: apparmorextraprofiles
#   notify:
#     - Reload apparmor

# - name: Restart AppArmor
#   when: apparmorprofilescopy.changed or apparmorextraprofiles.changed
#   ansible.builtin.systemd:
#     name: apparmor
#     state: reloaded
#     daemon_reload: true
#     enabled: true

# - name: Remove tempdir
#   ansible.builtin.file:
#     path: "{{ apparmor_profiles_tempdir.path }}"
#     state: absent
