---
- name: Disable remount
  file:
    path: /etc/remount-disable
    state: touch
    mode: 0444

- name: Install some hardering packages from whonix
  register: install_hardering
  until: install_hardering is succeeded
  apt:
    name:
      - jitterentropy-rngd
      - security-misc
      - tirdad
      - kloak
      - lkrg
      - dracut

- name: Disable hidepid service
  systemd:
    name: proc-hidepid.service
    enabled: false
    state: stopped
