- name: Disable remount
  file:
    path: /etc/remount-disable
    state: touch

- name: Install some hardering packages from whonix
  apt:
    name:
      - jitterentropy-rngd
      - security-misc
      - tirdad
      - kloak
#      - lkrg

- name: Disable hidepid service
  systemd:
    name: proc-hidepid.service
    enabled: no
    state: stopped