- name: Install xsettingsd
  package:
    name: xsettingsd
    state: present
  tags:
    - dependencies

- name: Copy xsettingsd config
  copy:
    src: xsettingsd
    dest: "/home/{{ username }}/.xsettingsd"
    mode: 0640
    owner: "{{ username }}"
    group: "{{ username }}"